---

libraries_apt:
  - unzip

robo3t_version    : "1.2.1"
robo3t_subversion : "3e50a65"
robo3t_lib        : "robo3t-{{ robo3t_version }}-linux-x86_64-{{ robo3t_subversion }}"

robo3t:
  url         : "https://download.robomongo.org/{{ robo3t_version }}/linux/"
  zip         : "{{ robo3t_lib }}.tar.gz"
  home        : "/usr/lib/robo3t"

desktop : "robo3t"

robo3t_connections:
  - host  : "gpc-mongodb-1.aat1.soa.indev01.aws.travisperkins.cloud"
    port  : "3306"
    user  : "pricetask_rw_ppd_upload"
    conns :
      - name: "uat1 1 - db1"
        db  : "pricetask_DB_uat_1"
      - name: "uat1 1 - db2"
        db  : "pricetask_DB_uat_2"
      - name: "uat1 1 - cfg"
        db  : "pricetask_DB_uat_config"

  - host  : "gpc-mongodb-2.aat1.soa.indev01.aws.travisperkins.cloud"
    port  : "3306"
    user  : "pricetask_rw_ppd_upload"
    conns :
      - name: "uat1 2 - db1"
        db  : "pricetask_DB_uat_1"
      - name: "uat1 2 - db2"
        db  : "pricetask_DB_uat_2"
      - name: "uat1 2 - cfg"
        db  : "pricetask_DB_uat_config"

  - host  : "gpc-mongodb-3.aat1.soa.indev01.aws.travisperkins.cloud"
    port  : "3306"
    user  : "pricetask_rw_ppd_upload"
    conns :
      - name: "uat1 3 - db1"
        db  : "pricetask_DB_uat_1"
      - name: "uat1 3 - db2"
        db  : "pricetask_DB_uat_2"
      - name: "uat1 3 - cfg"
        db  : "pricetask_DB_uat_config"

  - host  : "bc1mdbgpc11.fnt1.travisperkins.com"
    port  : "27017"
    user  : "pricetask_rw_uat"
    conns :
      - name: "onprem uat1 - db1"
        db  : "pricetask_DB_uat_1"
      - name: "onprem uat1 - db2"
        db  : "pricetask_DB_uat_2"
      - name: "onprem uat1 - cfg"
        db  : "pricetask_DB_uat_config"

