---

#################################################################

- name: "mkdirs"
  file:
    name    : "{{ item }}"
    state   : "directory"
    recurse : "yes"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  with_items:
    - "{{ intellij.home }}"
  tags:
    - developer
    - intellij

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  with_items: "{{ libraries_apt }}"
  tags:
    - developer
    - intellij

#################################################################

- name: "wget"
  get_url:
    url     : "{{ intellij.url }}{{ intellij.zip }}"
    dest    : "/tmp/{{ intellij.zip }}"
  creates: "{{ intellij.home }}/idea-IC-172.4343.14/"
  tags:
    - developer
    - intellij

- name: "unpack"
  unarchive:
    src     : "/tmp/{{ intellij.zip }}"
    dest    : "{{ intellij.home }}"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    creates : "{{ intellij.home }}/idea-IC-172.4343.14/"
  tags:
    - developer
    - intellij

#################################################################

