---

#################################################################

- name: "mkdirs"
  file:
    name    : "{{ item }}"
    state   : "directory"
    recurse : "yes"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  with_items:
    - "{{ intellij.home }}/{{ intellij_version }}"
  tags:
    - developer
    - intellij

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  with_items: "{{ libraries_apt }}"
  tags:
    - developer
    - intellij

#################################################################

- name: "unpack"
  unarchive:
    src         : "{{ intellij.url }}{{ intellij.zip }}"
    dest        : "{{ intellij.home }}/{{ intellij_version }}"
#    owner       : "{{ primary_user.id }}"
#    group       : "{{ primary_user.id }}"
    remote_src  : "yes"
    extra_opts  : [--strip-components=1]
    creates     : "{{ intellij.home }}/{{ intellij_version }}/bin/"
  become  : "{{ primary_user.id }}"
  tags:
    - developer
    - intellij

#################################################################

- name: "copy | config"
  template:
    src         : "jetbrains-idea-ce.desktop.j2"
    dest        : "/usr/share/applications/jetbrains-idea-ce.desktop"
    owner       : "{{ primary_user.id }}"
    group       : "{{ primary_user.id }}"
    mode        : "0644"
  tags:
    - developer
    - intellij

- name    : "cmd | add to launcher"
  script  : "{{ unity_launcher.script }}"
  become  : "{{ primary_user.id }}"
  tags:
    - developer
    - intellij

#################################################################

