---

#################################################################

- name: "mkdirs"
  file:
    name    : "{{ item }}"
    state   : "directory"
    recurse : "yes"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  with_items:
    - "{{ intellij.home }}/{{ intellij_version }}"
    - "{{ primary_user.home }}/.IdeaIC{{ intellij_year }}"
  tags:
    - developer
    - intellij

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  with_items: "{{ libraries_apt }}"
  tags:
    - developer
    - intellij

#################################################################

- name: "unpack | application"
  unarchive:
    src         : "{{ intellij.url }}{{ intellij.zip }}"
    dest        : "{{ intellij.home }}/{{ intellij_version }}"
    remote_src  : "yes"
    extra_opts  : [--strip-components=1]
    creates     : "{{ intellij.home }}/{{ intellij_version }}/bin/"
  become : "{{ primary_user.id }}"
  tags:
    - developer
    - intellij

- name: "unpack | application config"
  unarchive:
    src         : "files/config.tar.gz"
    dest        : "{{ primary_user.home }}/.IdeaIC{{ intellij_year }}"
    owner       : "{{ primary_user.id }}"
    group       : "{{ primary_user.id }}"
  tags:
    - developer
    - intellij

#################################################################

- name: "copy | desktop icon"
  template:
    src         : "jetbrains-idea-ce.desktop.j2"
    dest        : "/usr/share/applications/jetbrains-idea-ce.desktop"
    owner       : "{{ primary_user.id }}"
    group       : "{{ primary_user.id }}"
    mode        : "0644"
  tags:
    - developer
    - intellij

- name    : "cmd | unity | add to launcher"
  when    :
    - ansible_distribution      | lower == "ubuntu"
    - ansible_lsb.major_release | int   <  18
  script  : "{{ unity_launcher.script }}"
  become  : "{{ primary_user.id }}"
  tags:
    - developer
    - intellij

#################################################################

