---

#################################################################

- name: "mkdirs"
  file:
    name: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    mode: 0755
  with_items:
    - "{{ android.home }}"
    - "{{ intellij.home }}"
    - "{{ terraform.home }}"
    - "{{ gradle.home }}"

#################################################################

- name: "apt | install"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ libraries_apt }}"

- name: "pip | install"
  pip:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ libraries_pip }}"

#################################################################

- name: "gradle | wget"
  get_url:
    url: "{{ gradle.url }}{{ gradle.zip }}"
    dest: "/tmp/{{ gradle.zip }}"
  creates: "{{ gradle.home }}/gradle/"

- name: "gradle | unpack"
  unarchive:
    src: "/tmp/{{ gradle.zip }}"
    dest: "{{ gradle.home }}"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    creates: "{{ gradle.home }}/gradle/"

#################################################################

- name: "android | wget"
  get_url:
    url: "{{ android.url }}{{ android.zip }}"
    dest: "/tmp/{{ android.zip }}"
  creates: "{{ android.home }}/android-studio/"

- name: "android | unpack"
  unarchive:
    src: "/tmp/{{ android.zip }}"
    dest: "{{ android.home }}"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    creates: "{{ android.home }}/android-studio/"

#################################################################

- name: "intellij | wget"
  get_url:
    url: "{{ intellij.url }}{{ intellij.zip }}"
    dest: "/tmp/{{ intellij.zip }}"
  creates: "{{ intellij.home }}/idea-IC-172.4343.14/"

- name: "intellij | unpack"
  unarchive:
    src: "/tmp/{{ intellij.zip }}"
    dest: "{{ intellij.home }}"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    creates: "{{ intellij.home }}/idea-IC-172.4343.14/"

#################################################################

- name: "terraform | wget"
  get_url:
    url: "{{ terraform.url }}{{ terraform.zip }}"
    dest: "/tmp/{{ terraform.zip }}"
  creates: "{{ terraform.home }}/terraform"

- name: "terraform | unpack"
  unarchive:
    src: "/tmp/{{ terraform.zip }}"
    dest: "{{ terraform.home }}"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    creates: "{{ terraform.home }}/terraform"

#################################################################

- name: "docker | apt | key"
  apt_key:
    id: "{{ docker.key_id }}"
    keyserver: "{{ docker.key_server }}"
    state: present

- name: "docker | apt | repo"
  apt_repository:
    repo: "{{ docker.repo }}"
    state: present

- name: "docker | apt | install"
  apt:
    name: "{{ docker.apt }}"
    state: latest
    update_cache: yes
  notify: "docker | service | start"

#################################################################

