---

#################################################################

- name: "apt > install > prereq"
  apt:
    name          : "{{ libraries_apt }}"
    state         : "latest"
  tags:
    - "media"
    - "steam"

#################################################################

- name: "apt > install"
  apt:
    name    : "{{ steam.libraries.apt }}"
    state   : "present"
  tags:
    - "media"
    - "steam"

#################################################################

- name: "file > destroy files"
  with_items:
    - "{{ binme }}"
  file:
    path          : "{{ item }}"
    state         : "absent"
  tags:
    - "media"
    - "steam"

#################################################################

- name: "launcher > desktop icon"
  template:
    src   : "{{ desktop }}.desktop.j2"
    dest  : "/usr/share/applications/{{ desktop }}.desktop"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0644"
  tags:
    - "media"
    - "steam"
    - "launcher"

- name    : "launcher > add"
  become  : yes
  become_user  : "{{ primary_user.id }}"
  script  : "../../scripts/add_{{ desktop_environment }}_launcher.sh {{ desktop }}"
  changed_when: False
  tags:
    - "media"
    - "steam"
    - "launcher"

#################################################################

