---
# ################################################################

- name: "Apt > install > prereq"
  ansible.builtin.apt:
    name: "{{ libraries_apt }}"
    state: "latest"
  tags:
    - "media"
    - "steam"

#################################################################

- name: "Apt > install"
  ansible.builtin.apt:
    name: "{{ steam.libraries.apt }}"
    state: "present"
  tags:
    - "media"
    - "steam"

#################################################################

- name: "File > destroy files"
  with_items:
    - "{{ binme }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  tags:
    - "media"
    - "steam"

#################################################################

- name: "Launcher > desktop icon"
  ansible.builtin.template:
    src: "{{ desktop }}.desktop.j2"
    dest: "/usr/share/applications/{{ desktop }}.desktop"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    mode: "0644"
  tags:
    - "media"
    - "steam"
    - "launcher"

- name: "Launcher > add"
  become: true
  become_user: "{{ primary_user.id }}"
  ansible.builtin.script: "../../scripts/add_{{ desktop_environment }}_launcher.sh {{ desktop }}"
  changed_when: false
  tags:
    - "media"
    - "steam"
    - "launcher"

#################################################################
