---

#################################################################

- name: "apt | repo | prereq"
  with_items:
    - "{{ repositories_apt }}"
  apt_repository:
    repo          : "{{ item }}"
    state         : "present"
    update_cache  : "yes"
  tags:
    - media
    - steam

- name: "apt | upgrade"
  apt:
    update_cache  : "yes"
    upgrade       : "dist"
  tags:
    - media
    - steam

- name: "apt | install | prereq"
  apt:
    name          : "{{ libraries_apt }}"
    state         : "latest"
  tags:
    - media
    - steam

#################################################################

- name: "apt | install"
  apt:
    deb           : "{{ steam.deb }}"
  tags:
    - media
    - steam

#################################################################

- name: "file | destroy files"
  with_items:
    - "{{ binme }}"
  file:
    path          : "{{ item }}"
    state         : "absent"
  tags:
    - media
    - steam

#################################################################

- name    : "cmd | unity | add to launcher"
  when    :
    - ansible_distribution      | lower == "ubuntu"
    - ansible_lsb.major_release | int   <  18
  script  : "{{ unity_launcher.script }}"
  become  : "{{ primary_user.id }}"
  tags:
    - media
    - steam

#################################################################

