---

#################################################################

- name: "choco > install"
  win_chocolatey:
    name    : "{{ steam.libraries.choco }}"
    state   : "present"
  tags:
    - "media"
    - "steam"

#################################################################

