---
# ################################################################

- name: "Choco > install"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ steam.libraries.choco }}"
    state: "present"
  tags:
    - "media"
    - "steam"

#################################################################
