---

#################################################################

- name: "mkdirs"
  with_items:
    - "{{ android.home }}/{{ android_version }}"
  file:
    name    : "{{ item }}"
    state   : "directory"
    recurse : "yes"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  tags:
    - "developer"
    - "ide"
    - "android"

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ libraries_apt }}"
    state   : "latest"
  tags:
    - "developer"
    - "ide"
    - "android"

#################################################################

- name: "unpack"
  become : "{{ primary_user.id }}"
  unarchive:
    src         : "{{ android.url }}{{ android.zip }}"
    dest        : "{{ android.home }}/{{ android_version }}"
    remote_src  : "yes"
    creates     : "{{ android.home }}/{{ android_version }}/android-studio/bin/"
  tags:
    - "developer"
    - "ide"
    - "android"

#################################################################

- name: "launcher | desktop icon"
  template:
    src   : "{{ desktop }}.desktop.j2"
    dest  : "/usr/share/applications/{{ desktop }}.desktop"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0644"
  tags:
    - "developer"
    - "ide"
    - "android"
    - "launcher"

- name    : "launcher | add"
  become  : "{{ primary_user.id }}"
  script  : "../../../scripts/add_{{ desktop_environment }}_launcher.sh {{ desktop }}"
  tags:
    - "developer"
    - "ide"
    - "android"
    - "launcher"

#################################################################

