---

#################################################################

- name: "wget | deb"
  get_url:
    url   : "{{ chrome.url }}{{ chrome.file }}"
    dest  : "/tmp/{{ chrome.file }}"
  tags:
    - "browser"
    - "chrome"

- name: "apt | install"
  apt:
    deb   : "/tmp/{{ chrome.file }}"
    state : "present"
  tags:
    - "browser"
    - "chrome"

#################################################################

- name: "launcher | desktop icon"
  template:
    src   : "{{ desktop }}.desktop.j2"
    dest  : "/usr/share/applications/{{ desktop }}.desktop"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0644"
  tags:
    - "browser"
    - "chrome"
    - "launcher"

- name    : "launcher | add"
  become  : "{{ primary_user.id }}"
  script  : "../../scripts/add_{{ desktop_environment }}_launcher.sh {{ desktop }}"
  changed_when: False
  tags:
    - "browser"
    - "chrome"
    - "launcher"

#################################################################

