---

#################################################################

- name: "wget | deb"
  get_url:
    url   : "{{ chrome.url }}{{ chrome.file }}"
    dest  : "/tmp/{{ chrome.file }}"
  tags:
    - "browser"
    - "chrome"

- name: "apt | install"
  apt:
    deb   : "/tmp/{{ chrome.file }}"
    state : "present"
  tags:
    - "browser"
    - "chrome"

#################################################################

- name: "copy | desktop icon"
  template:
    src   : "google-chrome.desktop.j2"
    dest  : "/usr/share/applications/google-chrome.desktop"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0644"
  tags:
    - "browser"
    - "chrome"
    - "launcher"

- name    : "cmd | unity | add to launcher"
  when    :
    - ansible_distribution      | lower == "ubuntu"
    - ansible_lsb.major_release | int   <  18
  become  : "{{ primary_user.id }}"
  script  : "{{ launcher_favourite.unity }}"
  tags:
    - "browser"
    - "chrome"
    - "launcher"

- name    : "cmd | gnome | add to launcher"
  when    :
    - ansible_distribution      | lower == "ubuntu"
    - ansible_lsb.major_release | int   >= 18
  become  : "{{ primary_user.id }}"
  script  : "{{ launcher_favourite.gnome }}"
  tags:
    - "browser"
    - "chrome"
    - "launcher"

#################################################################

