---

#################################################################

- name: "choco > install"
  win_chocolatey:
    name    : "{{ libraries }}"
    state   : "present" 
  tags:
    - "browser"
    - "chrome"

#################################################################

