---

#################################################################

- name: "pip > install"
  pip:
    name      : "{{ ansible.libraries.pip }}"
    version   : u "{{ ansible_version }}"
    executable: "pip3"
  tags:
    - "{{ ansible.tags }}"

#################################################################

