---

#################################################################

- name: " "
  include_tasks : "{{ dist_family }}.yml"
  when:
    - dist_family in [ 'debian', 'windows' ]
  tags:
    - "shell"
    - "bash"
    - "powershell"
    - "proxy"

#################################################################

