---

#################################################################

- name: "powershell > config > profile"
  with_items:
    - "{{ primary_user }}"
  win_template:
    src   : "profile.ps1.j2"
    dest  : "%WINDIR%/System32/WindowsPowerShell/v1.0/profile.ps1"
  tags:
    - "shell"
    - "powershell"

#################################################################

