---

#################################################################

- name: "apt | install"
  when: proxy
  with_items:
    - "{{ libraries_apt }}"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  tags:
    - "proxy"

#################################################################

- name: "cntlm | config"
  when: proxy
  template:
    src     : "cntlm.j2"
    dest    : "/etc/cntlm.conf"
    owner   : "{{ root_user.id }}"
    group   : "{{ root_user.id }}"
  tags:
    - "proxy"

#################################################################

- name: "apt | config"
  when: proxy
  with_items:
    - { src: "apt",     dest: "01proxy"       }
    - { src: "apt_fix", dest: "99fixbadproxy" }
  template:
    src     : "{{ item.src }}.j2"
    dest    : "/etc/apt/apt.conf.d/{{ item.dest }}"
    owner   : "{{ root_user.id }}"
    group   : "{{ root_user.id }}"
  tags:
    - "proxy"

#################################################################

