---

#################################################################

- name: "copy | config | .bashrc"
  template:
    src: ".bashrc.j2"
    dest: "{{ item.home }}/.bashrc"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0644
  with_items: "{{ all_users }}"

- name: "copy | config | .bash_aliases"
  template:
    src: ".bash_aliases.j2"
    dest: "{{ item.home }}/.bash_aliases"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0644
  with_items: "{{ all_users }}"

- name: "copy | config | .bash_functions"
  template:
    src: ".bash_functions.j2"
    dest: "{{ item.home }}/.bash_functions"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0644
  with_items: "{{ all_users }}"

#################################################################

