---
# ################################################################

- name: "Mkdirs"
  with_items:
    - "{{ gradle.home }}"
  ansible.builtin.file:
    name: "{{ item }}"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    state: "directory"
  tags:
    - "{{ gradle.tags }}"

#################################################################

- name: "Apt > install"
  ansible.builtin.apt:
    name: "{{ gradle.libraries.apt }}"
    state: "latest"
  tags:
    - "{{ gradle.tags }}"

#################################################################

- name: "Unpack"
  ansible.builtin.unarchive:
    src: "{{ gradle.url }}{{ gradle.zip }}"
    dest: "{{ gradle.home }}"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    creates: "{{ gradle.home }}/gradle-{{ gradle_version }}/"
    remote_src: "yes"
  tags:
    - "{{ gradle.tags }}"

#################################################################

- name: "Config > mkdirs"
  with_items:
    - "{{ all_users }}"
  ansible.builtin.file:
    name: "{{ item.home }}/.gradle"
    owner: "{{ item.id }}"
    group: "{{ item.id }}"
    state: "directory"
  tags:
    - "{{ gradle.tags }}"
    - "proxy"

- name: "Config > properties"
  with_items:
    - "{{ all_users }}"
  ansible.builtin.template:
    src: "gradle.properties.j2"
    dest: "{{ item.home }}/.gradle/gradle.properties"
    owner: "{{ item.id }}"
    group: "{{ item.id }}"
  tags:
    - "{{ gradle.tags }}"
    - "proxy"

#################################################################
