---

#################################################################

- name: "apt | install"
  apt:
    deb: "{{ forticlient.url }}{{ forticlient.file }}"
    state: present
  tags:
    - forticlient

#################################################################

- name: "copy | config"
  template:
    src: "fctsslvpnhistory.j2"
    dest: "{{ primary_user.home }}/.fctsslvpnhistory"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    mode: 0644
  tags:
    - forticlient

#################################################################

