---

#################################################################

- name: "wget | deb"
  get_url:
    url: "{{ chrome.url }}{{ chrome.file }}"
    dest: "/tmp/{{ chrome.file }}"
  tags:
    - google
    - chrome

- name: "apt | install"
  apt:
    deb: "/tmp/{{ chrome.file }}"
    state: present
  tags:
    - google
    - chrome

#################################################################

- name    : "cmd | add to launcher"
  script  : "{{ unity_launcher.script }}"
  become  : "{{ primary_user.id }}"
  tags:
    - media
    - chrome

#################################################################

