---
# Tasks

- hosts: all
  become_user: root
  become_method: sudo
  connection: local
  gather_facts: yes

  vars:
  - libraries_apt_prereq:
    - libc6-i386
    - lib32z1
    - lib32ncurses5
    - lib32stdc++6

  - libraries_apt:
    - python-pip
    - python3-pip
    - vim
    - tree
    - vlc
    - xclip
    - baobab
    - ruby
    - indicator-sysmonitor
    - terminator
    - keychain

  - libraries_pip:
    - powerline-shell
    - awscli
    - ansible

  tasks:
  - name: "libraries | apt | prereqs"
    apt:
      name: "{{ item }}"
      state: "latest"
    with_items: "{{ libraries_apt_prereq }}"

  - name: "libraries | apt"
    apt:
      name: "{{ item }}"
      state: "latest"
    with_items: "{{ libraries_apt }}"

  - name: "libraries | pip"
    pip:
      name: "{{ item }}"
      state: "latest"
    with_items: "{{ libraries_pip }}"

