---

#################################################################

- name: " "
  include_tasks : "{{ dist_family }}.yml"
  when:
    - dist_family in [ 'debian' ]
    - gui | bool
  tags:
    - "desktop"

#################################################################

