---

ruby:
  libraries:
    apt:
      - "ruby"
    choco:
      - "ruby"
  gems:
    - "bundler"
    - "rake"
    - "minitest"

  tags:
    - developer
    - developer-lang
    - developer-lang-ruby
    - ruby
