---

#################################################################

- name: "mkdirs"
  file:
    name    : "{{ item }}"
    state   : "directory"
    recurse : "yes"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  with_items:
    - "{{ android.home }}/{{ android_version }}"
  tags:
    - developer
    - android

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  with_items: "{{ libraries_apt }}"
  tags:
    - developer
    - android

#################################################################

- name: "unpack"
  unarchive:
    src         : "{{ android.url }}{{ android.zip }}"
    dest        : "{{ android.home }}/{{ android_version }}"
    remote_src  : "yes"
    creates     : "{{ android.home }}/{{ android_version }}/android-studio/bin/"
  become : "{{ primary_user.id }}"
  tags:
    - developer
    - android

#################################################################

- name: "copy | config"
  template:
    src         : "jetbrains-android-studio.desktop.j2"
    dest        : "/usr/share/applications/jetbrains-android-studio.desktop"
    owner       : "{{ primary_user.id }}"
    group       : "{{ primary_user.id }}"
    mode        : "0644"
  tags:
    - developer
    - android

- name    : "cmd | add to launcher"
  script  : "{{ unity_launcher.script }}"
  become  : "{{ primary_user.id }}"
  tags:
    - developer
    - android

#################################################################

