---
# ################################################################

- name: "Apt > install"
  ansible.builtin.apt:
    name: "{{ libraries_apt }}"
    state: "latest"
  tags:
    - "browser"
    - "firefox"

#################################################################

- name: "Launcher > desktop icon"
  ansible.builtin.template:
    src: "{{ desktop }}.desktop.j2"
    dest: "/usr/share/applications/{{ desktop }}.desktop"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    mode: "0644"
  tags:
    - "browser"
    - "firefox"
    - "launcher"

- name: "Launcher > add"
  become: true
  become_user: "{{ primary_user.id }}"
  ansible.builtin.script: "../../scripts/add_{{ desktop_environment }}_launcher.sh {{ desktop }}"
  changed_when: false
  tags:
    - "browser"
    - "firefox"
    - "launcher"

#################################################################
