---

#################################################################

- name: "choco > install"
  win_chocolatey:
    name    : "{{ libraries_choco }}"
    state   : "present" 
  tags:
    - "browser"
    - "firefox"

#################################################################

