---

#################################################################

- name: "apt > install"
  apt:
    name    : "{{ python.libraries.apt }}"
    state   : "latest"
  tags:
    - "{{ python.tags }}"

- name: "apt > uninstall"
  apt:
    name    : "{{ python.libraries_remove.apt }}"
    state   : "latest"
  tags:
    - "{{ python.tags }}"

#################################################################

