---

#################################################################

- name: "apt > install"
  apt:
    name    : "{{ python.libraries.apt }}"
    state   : "latest"
  tags:
    - "{{ python.tags }}"

- name: "apt > uninstall"
  apt:
    name    : "{{ python.libraries_remove.apt }}"
    state   : "latest"
  tags:
    - "{{ python.tags }}"

#################################################################

- name: "pip > config"
  template:
    src     : "pip.conf.j2"
    dest    : "/etc/pip.conf"
    owner   : "{{ root_user.id }}"
    group   : "{{ root_user.id }}"
  tags:
    - "{{ python.tags }}"
    - "proxy"

#################################################################

