---
# ################################################################

- name: "Choco > install"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ python.libraries.choco }}"
    state: "latest"
  tags:
    - "{{ python.tags }}"

- name: "Choco > uninstall"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ python.libraries_remove.choco }}"
    state: "absent"
  tags:
    - "{{ python.tags }}"

#################################################################
