---

#################################################################

- name: "choco > install"
  win_chocolatey:
    name    : "{{ python.libraries.choco }}"
    state   : "latest"
  tags:
    - "{{ python.tags }}"

- name: "choco > uninstall"
  win_chocolatey:
    name    : "{{ python.libraries_remove.choco }}"
    state   : "absent"
  tags:
    - "{{ python.tags }}"

#################################################################

