---

#################################################################

- include_tasks : "{{ ansible_os_family | lower }}.yml"
  when    :
    - gui | bool
  tags:
    - "wallpaper"

#################################################################

