---

#################################################################

- name: "apt"
  apt:
    name  : "{{ packages.apt }}"
    state : "latest"
  tags:
    - "wallpaper"

- name: "pip"
  pip:
    name  : "{{ packages.pip }}"
    state : "latest"
  tags:
    - "wallpaper"

- name: "mkdir"
  with_items:
    - { d: "{{ wallpaper.install.dir   }}"                              }
    - { d: "{{ wallpaper.resource.dir  }}"                              }
    - { d: "{{ wallpaper.config.dir    }}", u: "{{ primary_user.id }}"  }
    - { d: "{{ wallpaper.service.dir   }}"                              }
  file:
    path  : "{{ item.d }}"
    state : "directory"
    owner : "{{ item.u | default(root_user.id)  }}"
    group : "{{ item.u | default(root_user.id)  }}"
    mode  : "0755"
  tags:
    - "wallpaper"

#################################################################

- name: "copy | config "
  template:
    src   : "{{ wallpaper.config.name }}.j2"
    dest  : "{{ wallpaper.config.dir  }}{{ wallpaper.config.name }}"
    owner : "{{ primary_user.id       }}"
    group : "{{ primary_user.id       }}"
    mode  : "0644"
  tags:
    - "wallpaper"

#################################################################

- name: "copy | wallpaper resources"
  copy:
    src   : "."
    dest  : "{{ wallpaper.resource.dir }}"
  tags:
    - "wallpaper"

- name: "copy | wallpaper service"
  template:
    src   : "{{ wallpaper.service.name }}.sh.j2"
    dest  : "{{ wallpaper.install.dir }}{{ wallpaper.service.name }}.sh"
    owner : "{{ root_user.id }}"
    group : "{{ root_user.id }}"
    mode  : "0755"
  notify: "wallpaper service | start"
  tags:
    - "wallpaper"

- name: "copy | systemd service"
  template:
    src   : "{{ wallpaper.service.name }}.service.j2"
    dest  : "{{ wallpaper.service.dir }}{{ wallpaper.service.name }}.service"
    owner : "{{ root_user.id }}"
    group : "{{ root_user.id }}"
    mode: "0755"
  notify: "wallpaper service | start"
  tags:
    - "wallpaper"

#################################################################

- name: "service | start"
  service:
    name    : "{{ wallpaper.service.name }}"
    enabled : yes
    state   : started
  tags:
    - "wallpaper"

#################################################################

