---

#################################################################

- name: "mkdir structure"
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0644
  with_items:
    - '/{{ systemd_dir}}'
    - '/{{ service_dir }}'
    - '/{{ wallpapers_dir }}'

#################################################################

- name: "copy | wallpaper resources"
  copy:
    src: '.'
    dest: '/{{ wallpapers_dir }}/'

- name: "copy | wallpaper service"
  template:
    src: "{{ service_dir }}/{{ service_name }}.sh.j2"
    dest: "/{{ service_dir }}/{{ service_name }}.sh"
    owner: root
    group: root
    mode: 0755
  notify: "service | start"

- name: "copy | systemd service"
  template:
    src: '{{ systemd_dir }}/{{ service_name }}.service.j2'
    dest: '/{{ systemd_dir }}/{{ service_name }}.service'
    owner: root
    group: root
    mode: 0755
  notify: "service | start"

#################################################################

- name: "service | start"
  service:
    name: '{{ service_name }}'
    enabled: yes
    state: started

#################################################################

