---

#################################################################

- name: "mkdir"
  with_items:
    - "{{ wallpaper.install.dir_win }}"
    - "{{ wallpaper.resource.dir_win }}"
    - "{{ wallpaper.config.dir }}"
  win_file:
    path  : "{{ item }}"
    state : "directory"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0755"
  tags:
    - "wallpaper"

#################################################################

- name: "resources > {{ wallpaper.resource.dir_win }}"
  win_copy:
    src   : "."
    dest  : "{{ wallpaper.resource.dir_win }}"
  tags:
    - "wallpaper"

#################################################################

- name: "service > script"
  win_template:
    src   : "{{ wallpaper.scripts.ps1 }}.j2"
    dest  : "{{ wallpaper.install.dir_win }}/{{ wallpaper.scripts.ps1 }}"
  tags:
    - "wallpaper"

#################################################################

