---
# ################################################################

- name: "Mkdirs"
  with_items:
    - "{{ all_users }}"
  ansible.builtin.file:
    dest: "{{ item.home }}/.config/keychain"
    state: "directory"
    owner: "{{ item.id }}"
    group: "{{ item.id }}"
    mode: "0755"
  tags:
    - "keychain"

#################################################################

- name: "Apt > install"
  ansible.builtin.apt:
    name: "{{ libraries_apt }}"
    state: "latest"
  tags:
    - "keychain"

#################################################################

- name: "Copy > config"
  with_items:
    - "{{ all_users }}"
  ansible.builtin.template:
    src: "config.j2"
    dest: "{{ item.home }}/.config/keychain/config"
    owner: "{{ item.id }}"
    group: "{{ item.id }}"
    mode: "0644"
  tags:
    - "keychain"

#################################################################
