---

#################################################################

- name: "apt | install"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ libraries_apt }}"

#################################################################

- name: "copy | config"
  template:
    src: "config.j2"
    dest: "{{ item.home }}/.config/keychain/config"
    owner: "{{ item.id }}"
    group: "{{ item.id }}"
    mode: 0644
  with_items: "{{ all_users }}"

#################################################################

