---

libraries_apt:
  - ssh

ssh_dirs:
  - ".ssh"

ssh_keys: []

ssh_templates:
  - "authorized_keys"
  - "config"

ssh_config:
  hosts:
    - name        : "192.168.1.90"
      psuedo_names: [ "pi", "retropie" ]
    - name        : "ssh-bastion.shared.devops.indev01.aws.travisperkins.cloud"
      psuedo_names: [ "bastion-indev" ]
    - name        : "ssh-bastion.shared.devops.intest01.aws.travisperkins.cloud"
      psuedo_names: [ "bastion-intest", "bastion" ]
    - name        : "lc0hymgt01.tpplc.local"
      psuedo_names: [ "bastion-onprem" ]
    - proxy       : "stest@ssh-bastion.shared.devops.indev01.aws.travisperkins.cloud"
      psuedo_names: [ "*.indev01.aws.travisperkins.cloud", "!ssh-bastion.shared.devops.indev01.aws.travisperkins.cloud" ]
    - proxy       : "stest@ssh-bastion.shared.devops.intest01.aws.travisperkins.cloud"
      psuedo_names: [ "*.intest01.aws.travisperkins.cloud", "!ssh-bastion.shared.devops.intest01.aws.travisperkins.cloud" ]

