---

#################################################################

- name: "apt | install"
  apt:
    deb: "{{ forticlient.url }}{{ forticlient.file }}"
    state: present
  tags:
    - forticlient

#################################################################

