---

#################################################################

- name: "install"
  pip :
    name    : "{{ item }}"
    state   : "latest"
  with_items: "{{ libraries_pip }}"
  tags:
    - developer
    - awscli

#################################################################

