---

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  with_items: "{{ libraries_apt }}"
  tags:
    - developer
    - terraform

#################################################################

- name: "install"
  git:
    repo: "{{ terraform.git  }}"
    dest: "{{ terraform.home }}"
  become    : "{{ primary_user.id }}"
  tags:
    - developer
    - terraform

- name      : "install version"
  command   : "{{ terraform.home }}/bin/tfenv install {{ item }}"
  become    : "{{ primary_user.id }}"
  with_items: "{{ terraform.version_install }}"
  tags:
    - developer
    - terraform

- name    : "use version"
  command : "{{ terraform.home }}/bin/tfenv use {{ terraform.version_use }}"
  become  : "{{ primary_user.id }}"
  tags:
    - developer
    - terraform

#################################################################

