---

#################################################################

- name: "mkdirs"
  file:
    name    : "{{ terraform.home }}/{{ item }}"
    state   : "directory"
    recurse : "yes"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  with_items:
    - "{{ terraform.versions }}"
  tags:
    - developer
    - terraform

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  with_items: "{{ libraries_apt }}"
  tags:
    - developer
    - terraform

#################################################################

- name: "unpack | application"
  unarchive:
    src         : "{{ terraform.url }}{{ terraform.zip }}"
    dest        : "{{ terraform.home }}/{{ item }}"
    remote_src  : "yes"
    creates     : "{{ terraform.home }}/{{ item }}/terraform"
  with_items:
    - "{{ terraform.versions }}"
  tags:
    - developer
    - terraform

#################################################################

- name: "symlink"
  file:
    src     : "{{ terraform.home }}/{{ terraform_version }}/terraform"
    dest    : "{{ terraform.home }}/terraform"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
    state   : "link"
    force   : "yes"
  tags:
    - developer
    - terraform

#################################################################

