---
# ################################################################

- name: "Apt > install"
  ansible.builtin.apt:
    name: "{{ maven.libraries.apt }}"
    state: "latest"
  tags:
    - "{{ maven.tags }}"

#################################################################

- name: "Config > mkdirs"
  with_items:
    - "{{ all_users }}"
  ansible.builtin.file:
    name: "{{ item.home }}/.m2"
    owner: "{{ item.id }}"
    group: "{{ item.id }}"
    state: "directory"
  tags:
    - "{{ maven.tags }}"
    - "proxy"

- name: "Config > properties"
  with_items:
    - "{{ all_users }}"
  ansible.builtin.template:
    src: "settings.xml.j2"
    dest: "{{ item.home }}/.m2/settings.xml"
    owner: "{{ item.id }}"
    group: "{{ item.id }}"
  tags:
    - "{{ maven.tags }}"
    - "proxy"

#################################################################
