---

#################################################################

- name: "apt > install"
  apt:
    name    : "{{ maven.libraries.apt }}"
    state   : "latest"
  tags:
    - "{{ maven.tags }}"

#################################################################

- name: "config > mkdirs"
  with_items:
    - "{{ all_users }}"
  file:
    name    : "{{ item.home }}/.m2"
    owner   : "{{ item.id   }}"
    group   : "{{ item.id   }}"
    state   : "directory"
  tags:
    - "{{ maven.tags }}"
    - "proxy"

- name: "config > properties"
  with_items:
    - "{{ all_users }}"
  template:
    src     : "settings.xml.j2"
    dest    : "{{ item.home }}/.m2/settings.xml"
    owner   : "{{ item.id   }}"
    group   : "{{ item.id   }}"
  tags:
    - "{{ maven.tags }}"
    - "proxy"

#################################################################

