---
# ################################################################

- name: "Apt > install"
  ansible.builtin.apt:
    deb: "{{ plex.deb }}"
  tags:
    - "media"
    - "plex"

#################################################################
