---

#################################################################

- name: "plex > apt key"
  apt_key:
    url     : "https://downloads.plex.tv/plex-keys/PlexSign.key"
    state   : "present"
  tags: "{{ plex.tags }}"

- name: "plex > apt source"
  apt_repository:
#    repo    : "deb [signed-by=/usr/share/keyrings/plex-archive-keyring.gpg] https://downloads.plex.tv/repo/deb public main"
    repo    : "deb https://downloads.plex.tv/repo/deb public main"
    state   : "present"
  tags: "{{ plex.tags }}"

- name: "plex > apt install"
  apt:
    name    : "plexmediaserver"
    state   : "present"
    update_cache: "yes"
  tags: "{{ plex.tags }}"

- name: "plex > add to group pi"
  user:
    name: plex
    groups: pi
    append: yes
  tags: "{{ plex.tags }}"

#################################################################

- name: "piplexed > create wifi disable/enable script"
  template:
    src   : "check_network.sh"
    dest  : "/opt/check_network.sh"
    mode  : "0755"
  tags: "{{ plex.tags }}"

- name: "piplexed > disable wifi when ethernet connected"
  cron:
    name: Enable/Disable Wifi
    minute: "*"
    job: "/opt/check_network.sh"
  tags: "{{ plex.tags }}"

#################################################################

- name: plex server > cron > restart
  cron:
    name: Restart server
    minute: 0
    hour: 4
    job: "/sbin/shutdown -r now"
  tags: "{{ plex.tags }}"

