---

#################################################################

- name: "apt | install"
  apt:
    deb           : "{{ plex.deb }}"
  tags:
    - "media"
    - "plex"

#################################################################

