---

#################################################################

- name: "choco > install"
  win_chocolatey:
    name    : "{{ plex.libraries.choco }}"
    state   : "present"
  tags:
    - "media"
    - "plex"

#################################################################

