---
# ################################################################

- name: "Symlinks"
  with_items:
    - "{{ retropie_shortcuts }}"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "pi"
    group: "pi"
    mode: "0775"
    state: "link"
    force: "yes"
  tags:
    - retropie
    - retropie-dirs

- name: "Mkdirs > general dirs"
  with_items:
    - "{{ retropie_dirs }}"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "pi"
    group: "pi"
    mode: "0775"
    state: "directory"
  tags:
    - retropie
    - retropie-dirs

- name: "Mkdirs > save and state dirs"
  when:
    - item[0].has_saves is defined
    - item[0].has_saves | bool
  with_nested:
    - "{{ retropie_emus }}"
    - ["states", "saves", "roms"]
  ansible.builtin.file:
    path: "{{ retropie_home }}/{{ item[1] }}/{{ item[0].name }}"
    owner: "pi"
    group: "pi"
    mode: "0775"
    state: "directory"
  tags:
    - retropie
    - retropie-dirs

#################################################################

- name: "Boot > capture partuuid"
  ansible.builtin.shell:
    cmd: "blkid | grep retropie | awk '{print $5}' | grep -oh '\\w\\w\\w\\w\\w\\w\\w\\w-\\w\\w'"
  register: disk_partuuid
  tags:
    - retropie
    - retropie-boot

- name: "Boot > cmdline.txt"
  when:
    - disk_partuuid.stdout is defined
    - disk_partuuid.stdout != ""
  ansible.builtin.template:
    src: "boot_cmdline.txt.j2"
    dest: "/boot/cmdline.txt"
    owner: "root"
    group: "root"
    mode: "0664"
  tags:
    - retropie
    - retropie-boot

- name: "Boot > config.txt"
  ansible.builtin.template:
    src: "boot_config.txt.j2"
    dest: "/boot/config.txt"
    owner: "root"
    group: "root"
    mode: "0664"
  tags:
    - retropie
    - retropie-boot

#################################################################

- name: "Wifi > set country"
  ansible.builtin.lineinfile:
    path: "/etc/wpa_supplicant/wpa_supplicant.conf"
    regexp: "^country="
    line: "country=GB"
  tags:
    - retropie
    - retropie-wifi

#################################################################

- name: "Pi user > bios > binary > apply"
  ansible.builtin.unarchive:
    src: "bin/bios_general.zip"
    dest: "{{ retropie_home }}/BIOS"
    owner: "pi"
    group: "pi"
    mode: "0775"
  tags:
    - retropie
    - retropie-pi

#################################################################

- name: "Personalisation > splashscreens > binary"
  ansible.builtin.unarchive:
    src: "bin/splashscreens.zip"
    dest: "{{ retropie_home }}/splashscreens"
    owner: "pi"
    group: "pi"
    mode: "0775"
    creates: "{{ retropie_home }}/splashscreens/retropie.mov"
  tags:
    - retropie
    - retropie-personalise

- name: "Personalisation > splashscreens > config"
  ansible.builtin.template:
    src: "splashscreen.list.j2"
    dest: "/etc/splashscreen.list"
    owner: "root"
    group: "root"
    mode: "0664"
  tags:
    - retropie
    - retropie-personalise

- name: "Personalisation > themes > binary"
  ansible.builtin.unarchive:
    src: "bin/themes.zip"
    dest: "/etc/emulationstation/themes"
    owner: "root"
    group: "root"
    mode: "0775"
  tags:
    - retropie
    - retropie-personalise

- name: "Personalisation > game images > binary"
  ansible.builtin.unarchive:
    src: "bin/game_images.zip"
    dest: "/opt/retropie/configs/all/emulationstation"
    owner: "pi"
    group: "pi"
  tags:
    - retropie
    - retropie-personalise

- name: "Personalisation > gamelists > makedirs"
  with_items:
    - "{{ retropie_emus }}"
  ansible.builtin.file:
    path: "/opt/retropie/configs/all/emulationstation/gamelists/{{ item.name }}"
    owner: "pi"
    group: "pi"
    mode: "0775"
    state: "directory"
  tags:
    - retropie
    - retropie-personalise

- name: "Personalisation > gamelists > config"
  with_items:
    - "{{ retropie_emus }}"
  ansible.builtin.copy:
    src: "gamelists/{{ item.name }}_gamelist.xml"
    dest: "/opt/retropie/configs/all/emulationstation/gamelists/{{ item.name }}/gamelist.xml"
    owner: "pi"
    group: "pi"
  tags:
    - retropie
    - retropie-personalise

#################################################################

- name: "Emulationstation > es emulated system > config > apply"
  ansible.builtin.template:
    src: "es_systems.cfg.j2"
    dest: "/etc/emulationstation/es_systems.cfg"
    owner: "root"
    group: "root"
    mode: "0664"
  tags:
    - retropie
    - retropie-es

#################################################################

- name: "Retropie > config > mkdirs"
  when:
    - item.has_saves is defined
    - item.has_saves | bool
  with_items:
    - "{{ retropie_emus }}"
  ansible.builtin.file:
    path: "{{ retropie_cfg }}/{{ item.name }}"
    state: "directory"
  tags:
    - retropie
    - retropie-cfg

- name: "Retropie > config > emu > retroarch.cfg"
  when:
    - item.has_saves is defined
    - item.has_saves | bool
  with_items:
    - "{{ retropie_emus }}"
  ansible.builtin.template:
    src: "retroarch_emu.j2"
    dest: "{{ retropie_cfg }}/{{ item.name }}/retroarch.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "Retropie > config > all > retroarch.cfg"
  ansible.builtin.template:
    src: "retroarch_all.j2"
    dest: "{{ retropie_cfg }}/all/retroarch.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "Retropie > config > all > retroarch-core-options.cfg"
  ansible.builtin.template:
    src: "retroarch_core.j2"
    dest: "{{ retropie_cfg }}/all/retroarch-core-options.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "Retropie > config > autoconf > apply"
  ansible.builtin.template:
    src: "autoconf.cfg.j2"
    dest: "{{ retropie_cfg }}/all/autoconf.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "Retropie > config > runcommand > apply"
  ansible.builtin.template:
    src: "runcommand.cfg.j2"
    dest: "{{ retropie_cfg }}/all/runcommand.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "Retropie > config > autostart > apply"
  ansible.builtin.template:
    src: "autostart.sh.j2"
    dest: "{{ retropie_cfg }}/all/autostart.sh"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "Retropie > config > scraper > apply"
  ansible.builtin.template:
    src: "scraper.cfg.j2"
    dest: "{{ retropie_cfg }}/all/scraper.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "Retropie > config > es settings > apply"
  ansible.builtin.template:
    src: "es_settings.cfg.j2"
    dest: "{{ retropie_cfg }}/all/emulationstation/es_settings.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-cfg

#################################################################

- name: "Controller > emulators"
  with_items:
    - "{{ retropie_controllers }}"
  ansible.builtin.template:
    src: "controller.j2"
    dest: "{{ retropie_cfg }}/all/retroarch/autoconfig/{{ item.name }}.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-controllers

- name: "Controller > emulationstation"
  ansible.builtin.template:
    src: "controller_emulationstation.j2"
    dest: "{{ retropie_cfg }}/all/emulationstation/es_input.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-controllers

#################################################################

- name: "N64 > change default emulator"
  ansible.builtin.lineinfile:
    path: "{{ retropie_n64.cfg }}/emulators.cfg"
    regexp: "^default"
    line: 'default = "lr-mupen64plus"'
  tags:
    - retropie
    - retropie-n64

- name: "N64 > mkdirs"
  ansible.builtin.file:
    path: "{{ retropie_cfg }}/n64/{{ retropie_n64.emu }}"
    owner: "pi"
    group: "pi"
    mode: "0775"
    state: "directory"
  tags:
    - retropie
    - retropie-n64

- name: "N64 > controller remap"
  ansible.builtin.template:
    src: "controller_n64.j2"
    dest: "{{ retropie_cfg }}/n64/{{ retropie_n64.emu }}/{{ retropie_n64.emu }}.rmp"
  tags:
    - retropie
    - retropie-n64
    - retropie-controllers

#################################################################

- name: "Psx > mkdirs"
  ansible.builtin.file:
    path: "{{ retropie_cfg }}/psx/{{ retropie_psx.emu }}"
    owner: "pi"
    group: "pi"
    mode: "0775"
    state: "directory"
  tags:
    - retropie
    - retropie-psx

- name: "Psx > controller remap"
  ansible.builtin.template:
    src: "controller_psx.j2"
    dest: "{{ retropie_cfg }}/psx/{{ retropie_psx.emu }}/{{ retropie_psx.emu }}.rmp"
  tags:
    - retropie
    - retropie-psx
    - retropie-controllers

#################################################################

- name: "Mkdirs > dreamcast"
  ansible.builtin.file:
    path: "{{ retropie_dreamcast.cfg }}/mappings"
    owner: "pi"
    group: "pi"
    mode: "0775"
    state: "directory"
  tags:
    - retropie
    - retropie-dreamcast

- name: "Dreamcast > config"
  ansible.builtin.template:
    src: "dreamcast_emu.cfg.j2"
    dest: "{{ retropie_dreamcast.cfg }}/emu.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-dreamcast

- name: "Dreamcast > controller memory cards"
  ansible.builtin.unarchive:
    src: "bin/dreamcast_vmu.zip"
    dest: "{{ retropie_dreamcast.cfg }}"
    creates: "{{ retropie_dreamcast.cfg }}/vmu_save_A1.bin"
  tags:
    - retropie
    - retropie-dreamcast

- name: "Dreamcast > controller"
  with_items:
    - { src: "xbox360", dest: "controller_xpad" }
    - { src: "xboxone", dest: "controller_generic" }
    - { src: "keyboard", dest: "keyboard" }
  ansible.builtin.template:
    src: "controller_dreamcast_{{ item.src }}.j2"
    dest: "{{ retropie_dreamcast.cfg }}/mappings/{{ item.dest }}.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-dreamcast
    - retropie-controllers

#################################################################

- name: "Nds > mkdirs"
  ansible.builtin.file:
    path: "{{ retropie_cfg }}/nds/{{ retropie_nds.emu }}/config"
    owner: "pi"
    group: "pi"
    mode: "0775"
    state: "directory"
  tags:
    - retropie
    - retropie-nds

- name: "Nds > config"
  ansible.builtin.template:
    src: "nds_cfg.j2"
    dest: "{{ retropie_nds.cfg }}/drastic.cfg"
    owner: "pi"
    group: "pi"
    mode: "0664"
  tags:
    - retropie
    - retropie-nds

#################################################################

- name: "Python scripts > git clone"
  become: "{{ primary_user.id }}"
  ansible.builtin.git:
    repo: "{{ retropie_git.url }}"
    dest: "{{ retropie_git.dest }}"
    version: "master"
  tags:
    - retropie
    - retropie-python

- name: "Python scripts > symlinks"
  ansible.builtin.file:
    src: "{{ retropie_git.src }}"
    dest: "{{ retropie_python.home }}"
    owner: "pi"
    group: "pi"
    mode: "0775"
    state: "link"
    force: "yes"
  tags:
    - retropie
    - retropie-python

- name: "Python scripts > mkdir"
  with_items:
    - "{{ retropie_python.bgm_home }}"
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "pi"
    group: "pi"
    mode: "0775"
    state: "directory"
  tags:
    - retropie
    - retropie-python

- name: "Python scripts > apt"
  ansible.builtin.apt:
    name: "{{ retropie_python.apt }}"
    state: "latest"
  tags:
    - retropie
    - retropie-python

- name: "Python scripts > resolve dependancies"
  ansible.builtin.pip:
    requirements: "{{ retropie_git.dest }}/requirements.txt"
    executable: "pip3"
  tags:
    - retropie
    - retropie-python

- name: "Python scripts > install background music"
  ansible.builtin.unarchive:
    src: "bin/bgm.zip"
    dest: "{{ retropie_python.bgm_home }}"
  tags:
    - retropie
    - retropie-python

- name: "Python scripts > set bgm, restart and lightshow scripts on start"
  ansible.builtin.template:
    src: "rc.local.j2"
    dest: "/etc/rc.local"
  tags:
    - retropie
    - retropie-python

#################################################################

- name: "Fba > install bios"
  ansible.builtin.unarchive:
    src: "bin/bios_fba.zip"
    dest: "{{ retropie_fba.home }}"
  tags:
    - retropie
    - retropie-fba

#################################################################

- name: "Steam > mkdir"
  when: retropie_enabled_steam | bool
  with_items:
    - "{{ retropie_steam.home }}"
    - "{{ retropie_steam.cfg }}"
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "pi"
    group: "pi"
    mode: "0775"
    state: "directory"
  tags:
    - retropie
    - retropie-steam

- name: "Steam > apt key"
  when: retropie_enabled_steam | bool
  ansible.builtin.apt_key:
    url: "http://archive.itimmer.nl/itimmer.gpg"
    state: "present"
  tags:
    - retropie
    - retropie-steam

- name: "Steam > apt source"
  when: retropie_enabled_steam | bool
  ansible.builtin.apt_repository:
    repo: "deb http://archive.itimmer.nl/raspbian/moonlight stretch main"
    state: "present"
  tags:
    - retropie
    - retropie-steam

- name: "Steam > apt install"
  when: retropie_enabled_steam | bool
  ansible.builtin.apt:
    name: "moonlight-embedded"
    state: "present"
    update_cache: "yes"
  tags:
    - retropie
    - retropie-steam

- name: "Steam > 'roms'"
  when: retropie_enabled_steam | bool
  with_items:
    - "{{ retropie_steam.modes }}"
  ansible.builtin.template:
    src: "steam.j2"
    dest: "{{ retropie_steam.home }}/{{ item.res }}_{{ item.fps }}fps.sh"
    owner: "pi"
    group: "pi"
    mode: "0775"
  tags:
    - retropie
    - retropie-steam

#################################################################
