---

#################################################################

- name: "apt | install"
  when:
    - item is iterable
  with_items:
    - "{{ libraries_apt }}"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  tags:
    - retropie

#################################################################

- name: "mkdirs"
  when:
    - item is iterable
  with_items:
    - "{{ retropie_dirs }}"
  file:
    name    : "{{ item         }}"
    owner   : "{{ root_user.id }}"
    group   : "{{ root_user.id }}"
    mode    : "0755"
    state   : "directory"
  tags:
    - retropie

#################################################################

- name: "copy | files"
  when:
    - item is iterable
  with_items:
    - "{{ retropie_files }}"
  copy:
    src     : "{{ item.src  }}"
    dest    : "{{ item.dest }}/{{ item.src }}"
    owner   : "{{ item.user }}"
    group   : "{{ item.user }}"
    mode    : "0664"
  tags:
    - retropie

#################################################################

- name: "copy | templates"
  when:
    - item is iterable
  with_items:
    - "{{ retropie_templates }}"
  template:
    src     : "{{ item.src  }}.j2"
    dest    : "{{ item.dest }}/{{ item.src }}"
    owner   : "{{ item.user }}"
    group   : "{{ item.user }}"
    mode    : "0664"
  tags:
    - retropie

#################################################################

- name: "pi user | apply bios"
  unarchive:
    src     : "bios.zip"
    dest    : "/home/pi/RetroPie/BIOS"
    owner   : "pi"
    group   : "pi"
  tags:
    - retropie

- name: "pi user | apply splashscreens"
  unarchive:
    src     : "splashscreens.zip"
    dest    : "/home/pi/RetroPie/splashscreens"
    owner   : "pi"
    group   : "pi"
  tags:
    - retropie

#################################################################

- name: "emulationstation | apply themes"
  unarchive:
    src     : "themes.zip"
    dest    : "/etc/emulationstation/themes"
    owner   : "root"
    group   : "root"
  tags:
    - retropie

- name: "emulationstation | apply emulated systems config"
  template:
    src     : "es_systems.cfg.j2"
    dest    : "/etc/emulationstation/es_systems.cfg"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie

#################################################################

