---

#################################################################

- name: "boot | cmdline | config | apply"
  template:
    src     : "boot_cmdline.txt.j2"
    dest    : "/boot/cmdline.txt"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie

- name: "boot | config | config | apply"
  template:
    src     : "boot_config.txt.j2"
    dest    : "/boot/config.txt"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie

#################################################################

- name: "pi user | bios | binary | apply"
  unarchive:
    src     : "bios.zip"
    dest    : "/home/pi/RetroPie/BIOS"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
  tags:
    - retropie

- name: "pi user | splashscreens | binary | apply"
  unarchive:
    src     : "splashscreens.zip"
    dest    : "/home/pi/RetroPie/splashscreens"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
  tags:
    - retropie

- name: "pi user | splashscreens | config | apply"
  template:
    src     : "splashscreen.list.j2"
    dest    : "/etc/splashscreen.list"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie

#################################################################

- name: "emulationstation | themes | binary | apply"
  unarchive:
    src     : "themes.zip"
    dest    : "/etc/emulationstation/themes"
    owner   : "root"
    group   : "root"
    mode    : "0775"
  tags:
    - retropie

- name: "emulationstation | es emulated system | config | apply"
  template:
    src     : "es_systems.cfg.j2"
    dest    : "/etc/emulationstation/es_systems.cfg"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie

#################################################################

- name: "retropie | config | retroarch | apply"
  template:
    src     : "retroarch.cfg.j2"
    dest    : "/opt/retropie/configs/all/retroarch.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie

- name: "retropie | config | runcommand | apply"
  template:
    src     : "runcommand.cfg.j2"
    dest    : "/opt/retropie/configs/all/runcommand.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie

- name: "retropie | config | autostart | apply"
  template:
    src     : "autostart.sh.j2"
    dest    : "/opt/retropie/configs/all/autostart.sh"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie

- name: "retropie | config | scraper | apply"
  template:
    src     : "scraper.cfg.j2"
    dest    : "/opt/retropie/configs/all/scraper.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie

- name: "retropie | config | controller | apply"
  template:
    src     : "controller.cfg.j2"
    dest    : "/opt/retropie/configs/all/retroarch/autoconfig/Xbox Wireless Controller.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie

- name: "retropie | config | es settings | apply"
  template:
    src     : "es_settings.cfg.j2"
    dest    : "/opt/retropie/configs/all/emulationstation/es_settings.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie

- name: "retropie | config | es input | apply"
  template:
    src     : "es_input.cfg.j2"
    dest    : "/opt/retropie/configs/all/emulationstation/es_input.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie

#################################################################

