---

#################################################################

- name: "symlinks"
  with_items:
    - "{{ retropie_shortcuts }}"
  file:
    src     : "{{ item.src  }}"
    dest    : "{{ item.dest }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "link"
  tags:
    - retropie
    - retropie-dirs

- name: "mkdirs"
  with_items:
    - "{{ retropie_dirs.save_dir }}"
    - "{{ retropie_dirs.state_dir }}"
  file:
    path    : "{{ item  }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "directory"
  tags:
    - retropie
    - retropie-dirs

#################################################################

- name: "boot | cmdline | config | apply"
  template:
    src     : "boot_cmdline.txt.j2"
    dest    : "/boot/cmdline.txt"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie
    - retropie-boot

- name: "boot | config | config | apply"
  template:
    src     : "boot_config.txt.j2"
    dest    : "/boot/config.txt"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie
    - retropie-boot

#################################################################

- name: "pi user | bios | binary | apply"
  unarchive:
    src     : "bios_general.zip"
    dest    : "/home/pi/RetroPie/BIOS"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
  tags:
    - retropie
    - retropie-pi

- name: "pi user | splashscreens | binary | apply"
  unarchive:
    src     : "splashscreens.zip"
    dest    : "/home/pi/RetroPie/splashscreens"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
  tags:
    - retropie
    - retropie-pi

- name: "pi user | splashscreens | config | apply"
  template:
    src     : "splashscreen.list.j2"
    dest    : "/etc/splashscreen.list"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie
    - retropie-pi

#################################################################

- name: "emulationstation | themes | binary | apply"
  unarchive:
    src     : "themes.zip"
    dest    : "/etc/emulationstation/themes"
    owner   : "root"
    group   : "root"
    mode    : "0775"
  tags:
    - retropie
    - retropie-es

- name: "emulationstation | es emulated system | config | apply"
  template:
    src     : "es_systems.cfg.j2"
    dest    : "/etc/emulationstation/es_systems.cfg"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie
    - retropie-es

#################################################################

- name: "retropie | config | retroarch | apply"
  template:
    src     : "retroarch.cfg.j2"
    dest    : "/opt/retropie/configs/all/retroarch.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | runcommand | apply"
  template:
    src     : "runcommand.cfg.j2"
    dest    : "/opt/retropie/configs/all/runcommand.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | autostart | apply"
  template:
    src     : "autostart.sh.j2"
    dest    : "/opt/retropie/configs/all/autostart.sh"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | scraper | apply"
  template:
    src     : "scraper.cfg.j2"
    dest    : "/opt/retropie/configs/all/scraper.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | controller | apply"
  template:
    src     : "controller.cfg.j2"
    dest    : "/opt/retropie/configs/all/retroarch/autoconfig/Xbox Wireless Controller.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | es settings | apply"
  template:
    src     : "es_settings.cfg.j2"
    dest    : "/opt/retropie/configs/all/emulationstation/es_settings.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | es input | apply"
  template:
    src     : "es_input.cfg.j2"
    dest    : "/opt/retropie/configs/all/emulationstation/es_input.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

#################################################################

- name: "python scripts | git clone"
  git:
    repo    : "{{ retropie_git.url  }}"
    dest    : "{{ retropie_git.dest }}"
    version : "master"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | symlinks"
  file:
    src     : "{{ retropie_git.src      }}"
    dest    : "{{ retropie_python.home  }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "link"
    force   : "yes"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | mkdir"
  with_items:
    - "{{ retropie_python.bgm_home }}"
  file:
    dest    : "{{ item }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "directory"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | resolve dependancies"
  pip:
    requirements : "{{ retropie_git.dest }}/requirements.txt"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | apt"
  with_items:
    - "{{ retropie_python.apt }}"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | install background music"
  unarchive:
    src     : "bgm.zip"
    dest    : "{{ retropie_python.bgm_home }}"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | set bgm, restart and lightshow scripts on start"
  template:
    src     : "rc.local.j2"
    dest    : "/etc/rc.local"
  tags:
    - retropie
    - retropie-python

#################################################################

- name: "fba | install bios"
  unarchive:
    src     : "bios_fba.zip"
    dest    : "{{ retropie_fba.home }}"
  tags:
    - retropie
    - retropie-fba

#################################################################

- name: "steam | apt key"
  apt_key:
    url     : "http://archive.itimmer.nl/itimmer.gpg"
    state   : "present"
  tags:
    - retropie
    - retropie-steam

- name: "steam | apt source"
  apt_repository:
    repo    : "deb http://archive.itimmer.nl/raspbian/moonlight stretch main"
    state   : "present"
  tags:
    - retropie
    - retropie-steam

- name: "steam | apt install"
  apt:
    name    : "moonlight-embedded"
    state   : "present"
    update_cache: "yes"
  tags:
    - retropie
    - retropie-steam

- name: "steam  | mkdir"
  with_items:
    - "{{ retropie_steam.home   }}"
    - "{{ retropie_steam.config }}"
  file:
    dest    : "{{ item }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "directory"
  tags:
    - retropie
    - retropie-steam

- name: "steam | 'roms'"
  with_items:
    - "{{ retropie_steam.modes }}"
  template:
    src     : "steam.j2"
    dest    : "{{ retropie_steam.home }}/{{ item.res }}_{{ item.fps }}fps.sh"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
  tags:
    - retropie
    - retropie-steam

#################################################################

