---
#################################################################

- name: "symlinks"
  with_items:
    - "{{ retropie_shortcuts }}"
  file:
    src     : "{{ item.src  }}"
    dest    : "{{ item.dest }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "link"
  tags:
    - retropie
    - retropie-dirs

- name: "mkdirs | save and state dirs"
  when:
    - item[0].has_saves is defined
    - item[0].has_saves
  with_nested:
    - "{{ retropie_emus }}"
    - [ "states", "saves", "roms" ]
  file:
    path    : "{{ retropie_home }}/{{ item[1] }}/{{ item[0].name }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "directory"
  tags:
    - retropie
    - retropie-dirs

#################################################################

- name: "boot | cmdline.txt"
  template:
    src     : "boot_cmdline.txt.j2"
    dest    : "/boot/cmdline.txt"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie
    - retropie-boot

- name: "boot | config.txt"
  template:
    src     : "boot_config.txt.j2"
    dest    : "/boot/config.txt"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie
    - retropie-boot

#################################################################

- name: "pi user | bios | binary | apply"
  unarchive:
    src     : "bin/bios_general.zip"
    dest    : "{{ retropie_home }}/BIOS"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
  tags:
    - retropie
    - retropie-pi

#################################################################

- name: "personalisation | splashscreens | binary"
  unarchive:
    src     : "bin/splashscreens.zip"
    dest    : "{{ retropie_home }}/splashscreens"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    creates : "{{ retropie_home }}/splashscreens/retropie.mov"
  tags:
    - retropie
    - retropie-personalise

- name: "personalisation | splashscreens | config"
  template:
    src     : "splashscreen.list.j2"
    dest    : "/etc/splashscreen.list"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie
    - retropie-personalise

- name: "personalisation | themes | binary"
  unarchive:
    src     : "bin/themes.zip"
    dest    : "/etc/emulationstation/themes"
    owner   : "root"
    group   : "root"
    mode    : "0775"
  tags:
    - retropie
    - retropie-personalise

- name: "personalisation | game images | binary"
  unarchive:
    src     : "bin/game_images.zip"
    dest    : "/opt/retropie/configs/all/emulationstation"
    owner   : "pi"
    group   : "pi"
  tags:
    - retropie
    - retropie-personalise

- name: "personalisation | gamelists | makedirs"
  with_items:
    - "{{ retropie_emus }}"
  file:
    path    : "/opt/retropie/configs/all/emulationstation/gamelists/{{ item.name }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "directory"
  tags:
    - retropie
    - retropie-personalise

- name: "personalisation | gamelists | config"
  with_items:
    - "{{ retropie_emus }}"
  copy:
    src     : "gamelists/{{ item.name }}_gamelist.xml"
    dest    : "/opt/retropie/configs/all/emulationstation/gamelists/{{ item.name }}/gamelist.xml"
    owner   : "pi"
    group   : "pi"
  tags:
    - retropie
    - retropie-personalise

#################################################################

- name: "emulationstation | es emulated system | config | apply"
  template:
    src     : "es_systems.cfg.j2"
    dest    : "/etc/emulationstation/es_systems.cfg"
    owner   : "root"
    group   : "root"
    mode    : "0664"
  tags:
    - retropie
    - retropie-es

#################################################################

- name: "retropie | config | mkdirs"
  when:
    - item.has_saves is defined
    - item.has_saves
  with_items:
    - "{{ retropie_emus }}"
  file:
    path    : "{{ retropie_cfg }}/{{ item.name }}"
    state   : "directory"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | emu | retroarch.cfg"
  when:
    - item.has_saves is defined
    - item.has_saves
  with_items:
    - "{{ retropie_emus }}"
  template:
    src     : "retroarch_emu.j2"
    dest    : "{{ retropie_cfg }}/{{ item.name }}/retroarch.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | all | retroarch.cfg"
  template:
    src     : "retroarch_all.j2"
    dest    : "{{ retropie_cfg }}/all/retroarch.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | all | retroarch-core-options.cfg"
  template:
    src     : "retroarch_core.j2"
    dest    : "{{ retropie_cfg }}/all/retroarch-core-options.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | autoconf | apply"
  template:
    src     : "autoconf.cfg.j2"
    dest    : "{{ retropie_cfg }}/all/autoconf.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | runcommand | apply"
  template:
    src     : "runcommand.cfg.j2"
    dest    : "{{ retropie_cfg }}/all/runcommand.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | autostart | apply"
  template:
    src     : "autostart.sh.j2"
    dest    : "{{ retropie_cfg }}/all/autostart.sh"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | scraper | apply"
  template:
    src     : "scraper.cfg.j2"
    dest    : "{{ retropie_cfg }}/all/scraper.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

- name: "retropie | config | es settings | apply"
  template:
    src     : "es_settings.cfg.j2"
    dest    : "{{ retropie_cfg }}/all/emulationstation/es_settings.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-cfg

#################################################################

- name: "controller | emulators"
  with_items:
    - "{{ retropie_controllers }}"
  template:
    src     : "controller.j2"
    dest    : "{{ retropie_cfg }}/all/retroarch/autoconfig/{{ item.name }}.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-controllers

- name: "controller | emulationstation"
  template:
    src     : "controller_emulationstation.j2"
    dest    : "{{ retropie_cfg }}/all/emulationstation/es_input.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-controllers

#################################################################

- name: "n64 | save locations | mupen64plus.cfg"
  lineinfile:
    path    : "{{ retropie_n64.cfg }}/mupen64plus.cfg"
    regexp  : "^SaveStatePath"
    line    : 'SaveStatePath   = "{{ retropie_n64.state }}"'
  tags:
    - retropie
    - retropie-n64

- name: "n64 | state locations | mupen64plus.cfg"
  lineinfile:
    path    : "{{ retropie_n64.cfg }}/mupen64plus.cfg"
    regexp  : "^SaveSRAMPath"
    line    : 'SaveSRAMPath    = "{{ retropie_n64.save  }}"'
  tags:
    - retropie
    - retropie-n64

- name: "n64 | "
  template:
    src     : "n64_auto_cfg.j2"
    dest    : "{{ retropie_cfg }}/n64/InputAutoCfg.ini"
  tags:
    - retropie
    - retropie-n64
    - retropie-controllers

#################################################################

- name: "psx | mkdirs"
  file:
    path    : "{{ retropie_cfg }}/psx/{{ retropie_psx.emu }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "directory"
  tags:
    - retropie
    - retropie-psx

- name: "psx | controller remap"
  template:
    src     : "controller_psx.j2"
    dest    : "{{ retropie_cfg }}/psx/{{ retropie_psx.emu }}/{{ retropie_psx.emu }}.rmp"
  tags:
    - retropie
    - retropie-psx
    - retropie-controllers

#################################################################

- name: "dreamcast | config"
  template:
    src     : "dreamcast_emu.cfg.j2"
    dest    : "{{ retropie_dreamcast.cfg }}/emu.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-dreamcast

- name: "dreamcast | controller memory cards"
  unarchive:
    src     : "bin/dreamcast_vmu.zip"
    dest    : "{{ retropie_dreamcast.cfg }}"
    creates : "{{ retropie_dreamcast.cfg }}/vmu_save_A1.bin"
  tags:
    - retropie
    - retropie-dreamcast

- name: "dreamcast | controller"
  with_items:
    - { src: "xbox360",   dest: "controller_xpad"     }
    - { src: "xboxone",   dest: "controller_generic"  }
    - { src: "keyboard",  dest: "keyboard"            }
  template:
    src     : "controller_dreamcast_{{ item.src }}.j2"
    dest    : "{{ retropie_dreamcast.cfg }}/mappings/{{ item.dest }}.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-dreamcast
    - retropie-controllers

#################################################################

- name: "nds | config"
  template:
    src     : "nds_cfg.j2"
    dest    : "{{ retropie_nds.cfg }}/drastic.cfg"
    owner   : "pi"
    group   : "pi"
    mode    : "0664"
  tags:
    - retropie
    - retropie-nds

#################################################################

- name: "python scripts | git clone"
  git:
    repo    : "{{ retropie_git.url  }}"
    dest    : "{{ retropie_git.dest }}"
    version : "master"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | symlinks"
  file:
    src     : "{{ retropie_git.src      }}"
    dest    : "{{ retropie_python.home  }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "link"
    force   : "yes"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | mkdir"
  with_items:
    - "{{ retropie_python.bgm_home }}"
  file:
    dest    : "{{ item }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "directory"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | apt"
  apt:
    name    : "{{ retropie_python.apt }}"
    state   : "latest"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | resolve dependancies"
  pip:
    requirements : "{{ retropie_git.dest }}/requirements.txt"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | install background music"
  unarchive:
    src     : "bin/bgm.zip"
    dest    : "{{ retropie_python.bgm_home }}"
  tags:
    - retropie
    - retropie-python

- name: "python scripts | set bgm, restart and lightshow scripts on start"
  template:
    src     : "rc.local.j2"
    dest    : "/etc/rc.local"
  tags:
    - retropie
    - retropie-python

#################################################################

- name: "fba | install bios"
  unarchive:
    src     : "bin/bios_fba.zip"
    dest    : "{{ retropie_fba.home }}"
  tags:
    - retropie
    - retropie-fba

#################################################################

- name: "steam | mkdir"
  with_items:
    - "{{ retropie_steam.home }}"
    - "{{ retropie_steam.cfg  }}"
  file:
    dest    : "{{ item }}"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
    state   : "directory"
  tags:
    - retropie
    - retropie-steam

- name: "steam | apt key"
  apt_key:
    url     : "http://archive.itimmer.nl/itimmer.gpg"
    state   : "present"
  tags:
    - retropie
    - retropie-steam

- name: "steam | apt source"
  apt_repository:
    repo    : "deb http://archive.itimmer.nl/raspbian/moonlight stretch main"
    state   : "present"
  tags:
    - retropie
    - retropie-steam

- name: "steam | apt install"
  apt:
    name    : "moonlight-embedded"
    state   : "present"
    update_cache: "yes"
  tags:
    - retropie
    - retropie-steam

- name: "steam | 'roms'"
  with_items:
    - "{{ retropie_steam.modes }}"
  template:
    src     : "steam.j2"
    dest    : "{{ retropie_steam.home }}/{{ item.res }}_{{ item.fps }}fps.sh"
    owner   : "pi"
    group   : "pi"
    mode    : "0775"
  tags:
    - retropie
    - retropie-steam

#################################################################

