---

#################################################################

- name: " "
  include_tasks : "{{ dist_family }}.yml"
  when:
    - dist_family in [ 'windows' ]
    - is_gui
  tags:
    - "{{ virtualbox.tags }}"

#################################################################

