---

#################################################################

- name: "choco > install"
  with_items:
    - "{{ virtualbox.libraries.choco }}"
  win_chocolatey:
    name    : "{{ item }}"
    state   : "latest"
  tags:
    - "{{ virtualbox.tags }}"

#################################################################

