---
# ################################################################

- name: "Choco > install"
  with_items:
    - "{{ virtualbox.libraries.choco }}"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: "latest"
  tags:
    - "{{ virtualbox.tags }}"

#################################################################
