---
# ################################################################

- name: "Apt > no gui"
  when:
    - libraries_apt | length > 0
  ansible.builtin.apt:
    name: "{{ libraries_apt }}"
    state: "latest"
  tags:
    - "general"

- name: "Apt > gui"
  when:
    - is_gui
    - libraries_apt_gui | length > 0
  ansible.builtin.apt:
    name: "{{ libraries_apt_gui }}"
    state: "latest"
  tags:
    - "general"

- name: "Pip > no gui"
  when:
    - libraries_pip | length > 0
  ansible.builtin.pip:
    name: "{{ libraries_pip }}"
    state: "latest"
    executable: "pip3"
  tags:
    - "general"

- name: "Pip > gui"
  when:
    - is_gui
    - libraries_pip_gui | length > 0
  ansible.builtin.pip:
    name: "{{ libraries_pip_gui }}"
    state: "latest"
    executable: "pip3"
  tags:
    - "general"

- name: "Snap > no gui"
  when:
    - libraries_snap | length > 0
  community.general.snap:
    name: "{{ libraries_snap }}"
    state: "present"
  tags:
    - "general"

- name: "Snap > gui"
  when:
    - is_gui
    - libraries_snap_gui | length > 0
  community.general.snap:
    name: "{{ libraries_snap_gui }}"
    state: "present"
  tags:
    - "general"

#################################################################

- name: "Additional mounts"
  when:
    - mount_points is iterable
  with_items:
    - "{{ mount_points }}"
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "UUID={{ item.uuid }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts | default(defaults.mount_opts) }}"
    state: "mounted"
  tags:
    - "general"
    - "mount"

#################################################################
