---

#################################################################

- name: "apt | install | no gui"
  apt:
    name  : "{{ libraries_apt }}"
    state : "latest"
  tags:
    - "general"

- name: "pip | install | no gui"
  pip:
    name  : "{{ libraries_pip }}"
    state : "latest"
  tags:
    - "general"

- name: "apt | install | gui"
  when: gui
  apt:
    name  : "{{ libraries_apt_gui }}"
    state : "latest"
  tags:
    - "general"

#################################################################

