---

#################################################################

- name: "apt | install"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ libraries_apt }}"

#################################################################

