---
# ################################################################

- name: "Choco > install"
  when:
    - libraries_choco | length > 0
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ libraries_choco }}"
    state: "present"
  tags:
    - "general"

- name: "Choco > install > gui"
  when:
    - is_gui
    - libraries_choco | length > 0
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ libraries_choco_gui }}"
    state: "present"
  tags:
    - "general"

#################################################################
