---

terraform:
  url             : "https://releases.hashicorp.com/terraform"
  home            : "/usr/lib/terraform"
  versions        :
    - "{{ terraform_version }}"
    - "1.0.6"
    - "0.15.5"
    - "0.14.11"
    - "0.13.7"
    - "0.12.31"
    - "0.11.15"
    - "0.10.8"

  libraries:
    apt:
      - unzip

  tags:
    - dev
    - dev-framework
    - dev-framework-terraform
    - terraform

