---
# ################################################################

- name: "Application > start"
  become: "yes"
  become_user: "{{ primary_user.id }}"
  ansible.builtin.shell: "nohup indicator-sysmonitor &"
  tags:
    - system-monitor

#################################################################
