---

#################################################################

- name  : "application > start"
  become: "yes"
  become_user: "{{ primary_user.id }}"
  shell : "nohup indicator-sysmonitor &"
  tags  :
    - system-monitor

#################################################################

