---

#################################################################

- name: "mkdirs"
  file:
    name    : "{{ item }}"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    state   : "directory"
  with_items:
    - "{{ gradle.home }}"
  tags:
    - developer
    - gradle

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  with_items: "{{ libraries_apt }}"
  tags:
    - developer
    - gradle

#################################################################

- name: "unpack"
  unarchive:
    src         : "{{ gradle.url }}{{ gradle.zip }}"
    dest        : "{{ gradle.home }}"
    owner       : "{{ primary_user.id }}"
    group       : "{{ primary_user.id }}"
    creates     : "{{ gradle.home }}/gradle-{{ gradle_version }}/"
    remote_src  : "yes"
  tags:
    - developer
    - gradle

#################################################################

