---

packages:
  apt:
    - "jq"
  pip:
    - "yq"

wallpaper:
  install :
    dir     : "/lib/ofi-wallpaper/"

  config  :
    name    : "config.yml"
    dir     : "{{ primary_user.home }}/.config/ofi-wallpaper/"

  resource:
    dir     : "/lib/ofi-wallpaper/resources"

  service :
    name    : "ofi-wallpaper"
    desc    : "OurFriendIrony Wallpaper"
    dir     : "/lib/systemd/system/"

