---

#################################################################

- name: "pkg > install"
  ansible.builtin.package:
    name    : "{{ ssh.libraries.apt }}"
    state   : "latest"
  when: 
    - pkg_mgr in [ 'apt' ]
  tags:
    - "{{ ssh.tags }}"

- name: "pkg > install"
  ansible.builtin.package:
    name    : "{{ ssh.libraries.pacman }}"
    state   : "latest"
  when: 
    - pkg_mgr in [ 'pacman' ]
  tags:
    - "{{ ssh.tags }}"

#################################################################

- name: "mkdirs"
  with_nested:
    - "{{ all_users }}"
    - "{{ ssh.dirs }}"
  file:
    name    : "{{ item[0].home }}/{{ item[1] }}"
    owner   : "{{ item[0].id }}"
    group   : "{{ item[0].id }}"
    mode    : "0755"
    state   : "directory"
  tags:
    - "{{ ssh.tags }}"

#################################################################

- name: "config > templates"
  with_nested:
    - "{{ all_users }}"
    - "{{ ssh.templates }}"
  template:
    src     : "{{ item[1] }}.j2"
    dest    : "{{ item[0].home }}/.ssh/{{ item[1] }}"
    owner   : "{{ item[0].id }}"
    group   : "{{ item[0].id }}"
    mode    : "0644"
  tags:
    - "{{ ssh.tags }}"

#################################################################

- name: "config > pub keys"
  with_nested:
    - "{{ all_users }}"
    - "{{ ssh_keys }}"
  template:
    src     : "pub.j2"
    dest    : "{{ item[0].home }}/.ssh/{{ item[1].name }}.pub"
    owner   : "{{ item[0].id }}"
    group   : "{{ item[0].id }}"
    mode    : "0644"
  tags:
    - "{{ ssh.tags }}"

#################################################################

- name: "config > .hushlogin"
  with_items:
    - "{{ all_users }}"
  copy:
    content : ""
    dest    : "{{ item.home }}/.hushlogin"
    owner   : "{{ item.id }}"
    group   : "{{ item.id }}"
    mode    : "0644"
    force   : "no"
  tags:
    - "{{ ssh.tags }}"

#################################################################

