---

#################################################################

- name: "service > restart"
  service:
    name    : "{{ wallpaper.service.name }}"
    enabled : yes
    state   : restarted
  tags:
    - "wallpaper"

#################################################################

