---
# ################################################################

- name: "Service > restart"
  ansible.builtin.service:
    name: "{{ wallpaper.service.name }}"
    enabled: true
    state: restarted
  tags:
    - "wallpaper"

#################################################################
