---

#################################################################

- name: "service | start"
  service:
    name: '{{ service_name }}'
    enabled: yes
    state: restarted

#################################################################

