---
# ################################################################

- name: "Apt > update cache"
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  tags:
    - "prereq"

- name: "Apt > install"
  ansible.builtin.apt:
    name: "{{ libraries_apt.all }}"
    state: "latest"
  tags:
    - "prereq"

- name: "Apt > install > ubuntu"
  when:
    - ansible_distribution      | lower == "ubuntu"
  ansible.builtin.apt:
    name: "{{ libraries_apt.ubuntu }}"
    state: "latest"
  tags:
    - "prereq"

- name: "Apt > install > ubuntu > gnome"
  when:
    - desktop_environment == "gnome"
    - is_gui
  ansible.builtin.apt:
    name: "{{ libraries_apt.ubuntu_gnome }}"
    state: "latest"
  tags:
    - "prereq"

- name: "Apt > autoclean"
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
  changed_when: false
  tags:
    - "prereq"

- name: Set keyboard layout
  with_items:
    - { key: "altgr", value: "The default for the keyboard layout", vtype: "select" }
    - { key: "compose", value: "No compose key", vtype: "select" }
    - { key: "ctrl_alt_bksp", value: "false", type: "boolean" }
    - { key: "variant", value: "English (UK)", vtype: "select" }
    - { key: "layout", value: "English (UK)", vtype: "select" }
    - { key: "model", value: "Generic 105-key PC (intl.)", vtype: "select" }
  ansible.builtin.debconf:
    name: "keyboard-configuration"
    question: "keyboard-configuration/{{ item.key }}"
    value: "{{ item.value }}"
    vtype: "{{ item.type | default('string') }}"
  tags:
    - "prereq"

- name: Generate locales
  ansible.builtin.debconf:
    name: locales
    question: locales/locales_to_be_generated
    value: en_GB.UTF-8 UTF-8
    vtype: multiselect
  tags:
    - "prereq"

- name: Set locale
  ansible.builtin.debconf:
    name: locales
    question: locales/default_environment_locale
    value: en_GB.UTF-8
    vtype: select
  tags:
    - "prereq"

#################################################################
