---

#################################################################

- name: "apt > update cache"
  apt:
    update_cache: yes
  changed_when: False
  tags:
    - "prereq"

- name: "apt > install"
  apt:
    name  : "{{ libraries_apt.all }}"
    state : "latest"
  tags:
    - "prereq"

- name: "apt > install > ubuntu"
  when:
    - ansible_distribution      | lower == "ubuntu"
  apt:
    name  : "{{ libraries_apt.ubuntu }}"
    state : "latest"
  tags:
    - "prereq"

- name: "apt > install > ubuntu > gnome"
  when:
    - desktop_environment == "gnome"
    - is_gui
  apt:
    name  : "{{ libraries_apt.ubuntu_gnome }}"
    state : "latest"
  tags:
    - "prereq"

- name: "apt > autoclean"
  apt:
    autoclean : yes
    autoremove: yes
  changed_when: False
  tags:
    - "prereq"

- name: Set keyboard layout
  with_items:
  - { key: "altgr",         value : "The default for the keyboard layout", vtype : "select" }
  - { key: "compose",       value : "No compose key",                      vtype : "select" }
  - { key: "ctrl_alt_bksp", value : "false",                               type: "boolean" }
  - { key: "variant",       value : "English (UK)",                        vtype : "select" }
  - { key: "layout",        value : "English (UK)",                        vtype : "select" }
  - { key: "model",         value : "Generic 105-key PC (intl.)",          vtype : "select" }
  debconf:
    name: "keyboard-configuration"
    question: "keyboard-configuration/{{ item.key }}"
    value: "{{ item.value }}"
    vtype: "{{ item.type | default('string') }}"
  tags:
    - "prereq"

#################################################################

