---

#################################################################

- name: "apt | update cache"
  apt:
    update_cache: yes
  tags:
    - "prereq"

- name: "apt | install"
  apt:
    name  : "{{ libraries_apt.all }}"
    state : "latest"
  tags:
    - "prereq"

- name: "apt | install | ubuntu"
  when:
    - ansible_distribution      | lower == "ubuntu"
  apt:
    name  : "{{ libraries_apt.ubuntu }}"
    state : "latest"
  tags:
    - "prereq"

- name: "apt | install | ubuntu | gnome"
  when:
    - ansible_distribution      | lower == "ubuntu"
    - ansible_lsb.major_release | int   >= 18
  apt:
    name  : "{{ libraries_apt.ubuntu_18 }}"
    state : "latest"
  tags:
    - "prereq"

- name: "apt | autoclean"
  apt:
    autoclean : yes
    autoremove: yes
  tags:
    - "prereq"

#################################################################

