---

#################################################################

- name: "apt | update cache"
  apt:
    update_cache: yes

- name: "apt | install | ubuntu"
  when: ansible_distribution | lower  == 'ubuntu'
  with_items: "{{ libraries_apt.ubuntu }}"
  apt:
    name: "{{ item }}"
    state: "latest"

- name: "apt | install"
  with_items: "{{ libraries_apt.all }}"
  apt:
    name: "{{ item }}"
    state: "latest"

- name: "apt | autoclean"
  apt:
    autoclean: yes
    autoremove: yes

#################################################################

