---

#################################################################

- name: "mkdirs"
  with_items:
    - "{{ git.home }}"
  file:
    name    : "{{ item }}"
    state   : "directory"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  tags:
    - "git"

#################################################################

- name: "pkg > install"
  ansible.builtin.package:
    name    : "{{ git.libraries }}"
    state   : "latest"
  tags:
    - "git"

#################################################################

- name: "config > .gitconfig"
  with_items:
    - "{{ all_users }}"
  template:
    src     : "gitconfig.j2"
    dest    : "{{ item.home }}/.gitconfig"
    owner   : "{{ item.id }}"
    group   : "{{ item.id }}"
    mode    : "0644"
  tags:
    - "git"
    - "proxy"

#################################################################

- name: "add repos"
  when:
    - git_repos is iterable
  become: yes
  become_user: "{{ primary_user.id }}"
  with_items:
    - "{{ git_repos }}"
  git:
    repo    : "{{ item.repo }}"
    dest    : "{{ git.home }}/{{ item.subdir }}"
    update  : "no"
  tags:
    - "git"

#################################################################

