---

#################################################################

- name: " "
  include_tasks : "{{ dist_family }}.yml"
  when:
    - dist_family in [ 'debian', 'windows' ]
  tags:
    - "git"
    - "proxy"

- name: " "
  include_tasks : "debian.yml"
  when:
    - dist_family in [ 'archlinux' ]
  tags:
    - "git"
    - "proxy"

#################################################################

