---

#################################################################

- name: "apt | install"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ libraries_apt }}"
  tags:
    - git

#################################################################

- name: "copy | config"
  template:
    src: ".gitconfig.j2"
    dest: "{{ item.home }}/.gitconfig"
    owner: "{{ item.id }}"
    group: "{{ item.id }}"
    mode: 0644
  with_items: "{{ all_users }}"
  tags:
    - git

#################################################################

