---

#################################################################

- name: "mkdirs"
  with_items:
    - "{{ git.home }}"
  file:
    name    : "{{ item }}"
    state   : "directory"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  tags:
    - "git"

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ libraries_apt }}"
    state   : "latest"
  tags:
    - "git"

#################################################################

- name: "copy | config"
  with_items:
    - "{{ all_users }}"
  template:
    src     : "gitconfig.j2"
    dest    : "{{ item.home }}/.gitconfig"
    owner   : "{{ item.id }}"
    group   : "{{ item.id }}"
    mode    : "0644"
  tags:
    - "git"
    - "proxy"

#################################################################

- name: "add git repos"
  when:
    - git_repos is iterable
  become: yes
  become_user: "{{ primary_user.id }}"
  with_items:
    - "{{ git_repos }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ git.home }}/{{ item.subdir }}"
  tags:
    - "git"

#################################################################

