---

#################################################################

- name: "mkdirs"
  with_items:
    - "{{ git.home }}"
  win_file:
    name    : "{{ item }}"
    state   : "directory"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  tags:
    - "git"

#################################################################

- name: "choco > install"
  win_chocolatey:
    name    : "{{ git.libraries }}"
    state   : "latest"
  tags:
    - "git"

#################################################################

- name: "copy > config"
  win_template:
    src     : "gitconfig.j2"
    dest    : "{{ primary_user.home }}/.gitconfig"
    owner   : "{{ primary_user.id   }}"
    group   : "{{ primary_user.id   }}"
    mode    : "0644"
  tags:
    - "git"
    - "proxy"

#################################################################

#- name: "git > add repos"
#  when:
#    - git_repos is iterable
#  become: yes
#  become_user: "{{ primary_user.id }}"
#  with_items:
#    - "{{ git_repos }}"
#  git:
#    repo    : "{{ item.repo }}"
#    dest    : "{{ git.home }}/{{ item.subdir }}"
#    update  : "no"
#  tags:
#    - "git"

#################################################################

