---

#################################################################

- name: "mkdirs"
  with_items:
    - "{{ postman.home }}"
  file:
    name    : "{{ item }}"
    state   : "directory"
    recurse : "yes"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  tags:
    - "{{ postman.tags }}"

#################################################################

- name: "apt > install"
  apt:
    name    : "{{ postman.libraries.apt }}"
    state   : "latest"
  tags:
    - "{{ postman.tags }}"

#################################################################

- name: "wget"
  become : yes
  become_user : "{{ primary_user.id }}"
  unarchive:
    src         : "{{ postman.url }}"
    dest        : "{{ postman.home }}/"
    remote_src  : "yes"
    extra_opts  : [--strip-components=1]
    creates     : "{{ postman.home }}/Postman"
  tags:
    - "{{ postman.tags }}"

#################################################################

- name: "launcher > desktop icon"
  template:
    src   : "{{ desktop }}.desktop.j2"
    dest  : "/usr/share/applications/{{ desktop }}.desktop"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0644"
  tags:
    - "{{ postman.tags }}"
    - "launcher"

- name: "launcher > add"
  become: yes
  become_user  : "{{ primary_user.id }}"
  script  : "../../scripts/add_{{ desktop_environment }}_launcher.sh {{ desktop }}"
  changed_when: False
  tags:
    - "{{ postman.tags }}"
    - "launcher"

#################################################################

