---

#################################################################

- name: "mkdirs"
  with_items:
    - "{{ wso2studio.home }}/{{ wso2studio_version }}"
  file:
    name    : "{{ item }}"
    state   : "directory"
    recurse : "yes"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  tags:
    - "developer"
    - "ide"
    - "wso2studio"

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ libraries_apt }}"
    state   : "latest"
  tags:
    - "developer"
    - "ide"
    - "wso2studio"

#################################################################

- name: "get | application"
  get_url:
    url         : "{{ wso2studio.url }}{{ wso2studio.zip }}"
    dest        : "/tmp/{{ wso2studio.zip }}"
    headers     : {Referer: "{{ wso2studio.referer }}" }
  tags:
    - "developer"
    - "ide"
    - "wso2studio"

- name: "unpack | application"
  become : "{{ primary_user.id }}"
  unarchive:
    src         : "/tmp/{{ wso2studio.zip }}"
    dest        : "{{ wso2studio.home }}/{{ wso2studio_version }}"
    creates     : "{{ wso2studio.home }}/{{ wso2studio_version }}/eclipse/"
  tags:
    - "developer"
    - "ide"
    - "wso2studio"

#################################################################

- name: "launcher | desktop icon"
  template:
    src   : "{{ desktop }}.desktop.j2"
    dest  : "/usr/share/applications/{{ desktop }}.desktop"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0644"
  tags:
    - "developer"
    - "ide"
    - "wso2studio"
    - "launcher"

- name    : "launcher | add"
  become  : "{{ primary_user.id }}"
  script  : "../../../scripts/add_{{ desktop_environment }}_launcher.sh {{ desktop }}"
  tags:
    - "developer"
    - "ide"
    - "wso2studio"
    - "launcher"

#################################################################

