---

#################################################################

- name: "apt > install"
  apt:
    name    : "{{ ruby.libraries.apt }}"
    state   : "latest"
  tags:
    - developer
    - developer-lang
    - developer-lang-ruby
    - ruby

- name: "gem > install"
  with_items:
    - "{{ ruby.gems }}"
  gem:
    name      : "{{ item }}"
    state     : "latest"
  tags:
    - developer
    - developer-lang
    - developer-lang-ruby
    - ruby

#################################################################

