---
# ################################################################

- name: "Groups > add"
  with_items:
    - "{{ all_users }}"
  ansible.builtin.group:
    name: "{{ item.id }}"
    state: "present"
  tags:
    - "users"

#################################################################

- name: "Users > add"
  with_items:
    - "{{ all_users }}"
  ignore_errors: true
  ansible.builtin.user:
    name: "{{ item.id }}"
    group: "{{ item.id }}"
    home: "{{ item.home }}"
    state: "present"
  tags:
    - "users"

#################################################################
