---

#################################################################

- name: "mkdir structure"
  file:
    path: "{{ java.home }}"
    state: directory
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    mode: 0755
  tags:
    - "java"

#################################################################

- name: "apt | repositories"
  when: not proxy
  apt_repository:
    repo  : "{{ java.ppa }}"
    state : "present"
  tags:
    - java

- name: "apt | repositories"
  when: proxy
  become: yes
  become_user: "{{ primary_user.id }}"
  shell: "sudo -E add-apt-repository {{ java.ppa }} -y"
  tags:
    - "java"

#################################################################

- name: "apt | install packages"
  with_items:
    - "{{ libraries_apt }}"
  apt:
    name: "{{ item }}"
    state: latest
  tags:
    - "java"

#################################################################

- name: "symlink | set version"
  file:
    src: "{{ java.home }}/{{ java.default }}"
    dest: "{{ java.home }}/java"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    state: link
  tags:
    - "java"

#################################################################

