---

#################################################################

- name: "mkdir structure"
  file:
    path: "{{ java.home }}"
    state: directory
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    mode: 0755
  tags:
    - java

#################################################################

- name: "apt | repositories"
  apt_repository:
    repo: "{{ java.ppa }}"
  tags:
    - java

#################################################################

- name: "apt | install packages"
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ libraries_apt }}"
  tags:
    - java

#################################################################

- name: "symlink | set version"
  file:
    src: "{{ java.home }}/{{ java.default }}"
    dest: "{{ java.home }}/java"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    state: link
  tags:
    - java

#################################################################

