---

repositories_apt:
  - "ppa:xorg-edgers/ppa"

libraries_apt:
  - "libgl1-mesa-dri:i386"
  - "libgl1-mesa-glx:i386"
  - "libc6:i386"

steam:
  deb     : "https://steamcdn-a.akamaihd.net/client/installer/steam.deb"

binme:  # without destroying these steam wont start up [after installation]
  - "~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6"
  - "~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libgcc_s.so.1"

