---

repositories_apt:
  - "ppa:xorg-edgers/ppa"

libraries_apt:
  - "libgl1-mesa-dri:i386"
  - "libgl1-mesa-glx:i386"
  - "libc6:i386"

steam:
  deb     : "https://steamcdn-a.akamaihd.net/client/installer/steam.deb"

