---

#################################################################

- name: "apt > install"
  apt:
    name  : "{{ libraries_apt }}"
    state : "latest"
  register: apt_installed
  tags:
    - "terminator"

#################################################################
# Terminator 1.9.1 doesn't work with python3, so rig it for now

- name: "apt > get version"
  when: apt_installed.changed | bool
  command: "apt list terminator | grep terminator | awk '{print $2}'"
  register: result
  tags:
    - "terminator"

- name: "bugfix"
  when:
    - result.stdout is defined
    - result.stdout is search('1.91-1')
  lineinfile:
    path    : /usr/bin/terminator
    regexp  : "^#!/usr/bin/python"
    line    : "#!/usr/bin/python2"
  tags:
    - "terminator"

#################################################################

- name: "mkdir"
  file:
    path  : "{{ primary_user.home }}/.config/terminator"
    state : directory
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : 0755
  tags:
    - "terminator"

- name: "copy > config"
  template:
    src   : "config.j2"
    dest  : "{{ primary_user.home }}/.config/terminator/config"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : 0644
  tags:
    - "terminator"

#################################################################

- name: "launcher > desktop icon"
  template:
    src   : "{{ desktop }}.desktop.j2"
    dest  : "/usr/share/applications/{{ desktop }}.desktop"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0644"
  tags:
    - "terminator"
    - "launcher"

- name    : "launcher > add"
  become : yes
  become_user : "{{ primary_user.id }}"
  script  : "../../scripts/add_{{ desktop_environment }}_launcher.sh {{ desktop }}"
  changed_when: False
  tags:
    - "terminator"
    - "launcher"

#################################################################

