---

#################################################################

- name: "apt | install"
  with_items:
    - "{{ libraries_apt }}"
  apt:
    name  : "{{ item }}"
    state : "latest"
  tags:
    - "terminator"

#################################################################

- name: "mkdir"
  file:
    path  : "{{ primary_user.home }}/.config/terminator"
    state : directory
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : 0755
  tags:
    - "terminator"

- name: "copy | config"
  template:
    src   : "config.j2"
    dest  : "{{ primary_user.home }}/.config/terminator/config"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : 0644
  tags:
    - "terminator"

#################################################################

- name    : "copy | desktop icon"
  template:
    src   : "terminator.desktop.j2"
    dest  : "/usr/share/applications/terminator.desktop"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0644"
  tags:
    - "terminator"

- name    : "cmd | unity | add to launcher"
  when    :
    - ansible_distribution      | lower == "ubuntu"
    - ansible_lsb.major_release | int   <  18
  become  : "{{ primary_user.id }}"
  script  : "{{ unity_launcher.script }}"
  tags:
    - "terminator"

#################################################################

