---

libraries_apt:
  - unzip

pycharm_year       : "2018.1"
pycharm_subversion : "2"
pycharm_version    : "{{ pycharm_year }}.{{ pycharm_subversion }}"

pycharm:
  url     : "https://download-cf.jetbrains.com/python/"
  zip     : "pycharm-community-{{ pycharm_version }}.tar.gz"
  home    : "/usr/lib/pycharm"

launcher_favourite:
  unity  : "../../scripts/add_unity_launcher.sh jetbrains-pycharm-ce"
  gnome  : "../../scripts/add_gnome_launcher.sh jetbrains-pycharm-ce"

