---
# ################################################################

- name: "Mkdir > resolv.conf"
  with_items:
    - "/run/systemd/resolve"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ root_user.id }}"
    group: "{{ root_user.id }}"
    state: "directory"
  tags:
    - "network"
    - "dns"

- name: "Config > resolv.conf"
  with_items:
    - "/etc"
    - "/run/systemd/resolve"
  ansible.builtin.template:
    src: "resolv.conf.j2"
    dest: "{{ item }}/resolv.conf"
    owner: "{{ root_user.id }}"
    group: "{{ root_user.id }}"
  tags:
    - "network"
    - "dns"

#################################################################

- name: "Config > nsswitch.conf"
  with_items:
    - "/etc"
  ansible.builtin.template:
    src: "nsswitch.conf.j2"
    dest: "{{ item }}/nsswitch.conf"
    owner: "{{ root_user.id }}"
    group: "{{ root_user.id }}"
  tags:
    - "network"
    - "dns"

#################################################################
