---

#################################################################

- name: "18.04 | fix resolve.conf"
  when:
    - ansible_distribution_version == "18.04"
  file:
    src     : "/run/systemd/resolve/resolv.conf"
    dest    : "/etc/resolv.conf"
    state   : "link"
    force   : "yes"
  tags:
    - "network"
    - "dns"

#################################################################

- name: "18.04 | fix resolve.conf"
  lineinfile:
    path    : "/etc/resolv.conf"
    regexp  : "^search lan"
    line    : "search lan{% for i in dns_search_additions %} {{i}}{%endfor%}"
  tags:
    - "network"
    - "dns"

#################################################################

