---

#################################################################

- name: "rbenv > install"
  become: yes
  become_user: "{{ primary_user.id }}"
  git:
    repo: "{{ ruby.rbenv.url }}"
    dest: "{{ primary_user.home }}/{{ ruby.rbenv.home }}"
  tags:
    - "{{ ruby.tags }}"

- name: "mkdirs"
  file:
    name    : "{{ ruby.rbbuild.home }}"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
    state   : "directory"
  tags:
    - "{{ ruby.tags }}"

- name: "rbenv > install"
  become: yes
  become_user: "{{ primary_user.id }}"
  git:
    repo: "{{ ruby.rbbuild.url }}"
    dest: "{{ primary_user.home }}/{{ ruby.rbbuild.home }}"
  tags:
    - "{{ ruby.tags }}"

#- name: "rbenv > install"
#  apt:
#    name    : "{{ ruby.libraries.apt }}"
#    state   : "latest"
#  tags:
#    - "{{ ruby.tags }}"

#- name: "rbenv > init"
#  become: yes
#  become_user: "{{ primary_user.id }}"
#  shell: "rbenv init"
#  tags:
#    - "{{ ruby.tags }}"

#################################################################

#- name: "ruby > install"
#  become: yes
#  become_user: "{{ primary_user.id }}"
#  shell: "rbenv install {{ ruby_version }}"
#  tags:
#    - "{{ ruby.tags }}"

#################################################################

#- name: "gem > install"
#  with_items:
#    - "{{ ruby.gems }}"
#  become: yes
#  become_user: "{{ primary_user.id }}"
#  gem:
#    name      : "{{ item }}"
#    state     : "latest"
#  tags:
#    - "{{ ruby.tags }}"

#################################################################

