---

#################################################################

- name: "apt > install"
  apt:
    name    : "{{ ruby.libraries.apt }}"
    state   : "latest"
  tags:
    - "{{ ruby.tags }}"

- name: "gem > install"
  with_items:
    - "{{ ruby.gems }}"
  become: yes
  become_user: "{{ primary_user.id }}"
  gem:
    name      : "{{ item }}"
    state     : "latest"
  tags:
    - "{{ ruby.tags }}"

#################################################################

