---

#################################################################

- name: "choco > install"
  win_chocolatey:
    name    : "{{ ruby.libraries.choco }}"
    state   : "latest"
  tags:
    - "{{ ruby.tags }}"

#- name: "gem > install"
#  with_items:
#    - "{{ ruby.gems }}"
#  win_command: "gem install {{ item }}"
#  tags:
#    - "{{ ruby.tags }}"

#################################################################

