---

transmission:
  dir:
    core        : /home/pi/transmission
    downloading : /home/pi/transmission/downloading
    complete    : /home/pi/transmission/complete
    install     : /opt/transmission-api
  services:
  - transmission-api
  - transmission-daemon
  - transmission-migration

