---

#################################################################

- name: "apt | install | prereq"
  with_items:
    - "{{ libraries_apt }}"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  tags:
    - "developer"
    - "docker"

#################################################################

- name: "pip | install | prereq"
  with_items:
    - "{{ libraries_pip }}"
  pip:
    name    : "{{ item }}"
    state   : "latest"
  tags:
    - "developer"
    - "docker"

#################################################################

- name: "apt | key"
  apt_key:
    url           : "{{ docker.key_server }}"
    id            : "{{ docker.key_id }}"
    state         : "present"
  tags:
    - "developer"
    - "docker"

- name: "apt | repo"
  apt_repository:
    repo          : "{{ docker.repo }}"
    state         : "present"
  tags:
    - "developer"
    - "docker"

- name: "apt | install"
  with_items:
    - "{{ docker.apts }}"
  apt:
    name          : "{{ item }}"
    state         : "latest"
    update_cache  : "yes"
  tags:
    - "developer"
    - "docker"

#################################################################

- name: "group"
  user:
    name          : "{{ primary_user.id }}"
    groups        : "docker"
    append        : "yes"
  tags:
    - "developer"
    - "docker"

#################################################################

- name: "images | install"
  with_items:
    - "{{ docker_images }}"
  docker_image:
    name          : "{{ item.name }}"
    tag           : "{{ item.version }}"
  tags:
    - "developer"
    - "docker"

#################################################################

- name: "proxy | mkdirs"
  with_items:
    - "{{ all_users }}"
  file:
    name    : "{{ item.home }}/.docker"
    owner   : "{{ item.id   }}"
    group   : "{{ item.id   }}"
    state   : "directory"
  tags:
    - "developer"
    - "docker"
    - "proxy"

- name: "proxy | config"
  when: proxy
  with_items:
    - "{{ all_users }}"
  template:
    src     : "config.json.j2"
    dest    : "{{ item.home }}/.docker/config.json"
    owner   : "{{ item.id   }}"
    group   : "{{ item.id   }}"
  tags:
    - "developer"
    - "docker"
    - "proxy"

#################################################################

