---

- name: "Distribution"
  debug :
    msg : "{{ ansible_distribution_version }} {{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
  tags: [ "always" ]

- name: "VM Status"
  debug:
    msg: "{{ ansible_virtualization_role }} [{{ ansible_virtualization_type }}]"
  tags: [ "always" ]

- name: "Desktop Environment"
  debug:
    msg: "{{ lookup('env', 'XDG_CURRENT_DESKTOP') }}"
  tags: [ "always" ]

- name: "Check Ansible Version >= {{ min_ansible_version }}"
  assert:
    that: "ansible_version.full is version_compare('{{ min_ansible_version }}', '>=')"
    msg : "You must be running at least version {{ min_ansible_version }}"
  tags: [ "always" ]

