---

#################################################################

- name: "apt > install"
  apt:
    name    : "{{ terraform.libraries.apt }}"
    state   : "latest"
  tags:
    - "{{ terraform.tags }}"

#################################################################

- name: "tfenv > install"
  become: yes
  become_user: "{{ primary_user.id }}"
  git:
    repo: "{{ terraform.url }}"
    dest: "{{ primary_user.home }}/{{ terraform.home }}"
  tags:
    - "{{ terraform.tags }}"

#################################################################

- name: "mkdirs"
  file:
    name    : "{{ primary_user.home }}/{{ terraform.home }}/versions"
    state   : "directory"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  tags:
    - "{{ terraform.tags }}"

- name: "terraform > install"
  with_items: "{{ terraform.versions }}"
  become: yes
  become_user: "{{ primary_user.id }}"
  shell:
    chdir: "{{ primary_user.home }}/{{ terraform.home }}/versions"
    cmd: "PATH=\"{{ primary_user.home }}/{{ terraform.home }}:${PATH}\" {{ primary_user.home }}/{{ terraform.home }}/bin/tfenv install {{ item }}"
    creates: "{{ item }}"
  tags:
    - "{{ terraform.tags }}"

- name: "terraform > set version"
  become: yes
  become_user: "{{ primary_user.id }}"
  shell:
    cmd: "{{ primary_user.home }}/{{ terraform.home }}/bin/tfenv use {{ terraform_version }}"
  tags:
    - "{{ terraform.tags }}"

#################################################################

