---
# ################################################################

- name: "Apt > install"
  ansible.builtin.apt:
    name: "{{ terraform.libraries.apt }}"
    state: "latest"
  tags:
    - "{{ terraform.tags }}"

#################################################################

- name: "Tfenv > install"
  become: true
  become_user: "{{ primary_user.id }}"
  ansible.builtin.git:
    repo: "{{ terraform.url }}"
    dest: "{{ primary_user.home }}/{{ terraform.home }}"
  tags:
    - "{{ terraform.tags }}"

#################################################################

- name: "Mkdirs"
  ansible.builtin.file:
    name: "{{ primary_user.home }}/{{ terraform.home }}/versions"
    state: "directory"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    mode: "0755"
  tags:
    - "{{ terraform.tags }}"

- name: "Terraform > install"
  with_items: "{{ terraform.versions }}"
  become: true
  become_user: "{{ primary_user.id }}"
  ansible.builtin.shell:
    chdir: "{{ primary_user.home }}/{{ terraform.home }}/versions"
    cmd: "PATH=\"{{ primary_user.home }}/{{ terraform.home }}:${PATH}\" {{ primary_user.home }}/{{ terraform.home }}/bin/tfenv install {{ item }}"
    creates: "{{ item }}"
  tags:
    - "{{ terraform.tags }}"

- name: "Terraform > set version"
  become: true
  become_user: "{{ primary_user.id }}"
  ansible.builtin.command:
    cmd: "{{ primary_user.home }}/{{ terraform.home }}/bin/tfenv use {{ terraform_version }}"
  tags:
    - "{{ terraform.tags }}"

#################################################################
