---

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ tomcat }}"
    state   : "latest"
  tags:
    - developer
    - tomcat

#################################################################

- name: "config"
  template:
    src   : "{{ item.name }}.j2"
    dest  : "{{ item.dir }}/{{ item.name }}"
    owner : "{{ root_user.id }}"
    group : "{{ tomcat }}"
  with_items: "{{ tomcat_templates }}"
  notify    : "tomcat service | start"
  tags:
    - developer
    - tomcat

#################################################################

