---

#################################################################

dependencies:
  - role: "browser/chrome"
  - role: "browser/firefox"

#################################################################

