---

#################################################################

- name: "choco > install"
  win_chocolatey:
    name    : "{{ libraries }}"
    state   : "latest"
  tags:
    - "vim"

#################################################################

- name: "config > .vimrc"
  with_items:
    - "{{ primary_user }}"
  win_template:
    src   : "vimrc.j2"
    dest  : "{{ item.home }}/.vimrc"
    newline_sequence: "\n"
  tags:
    - "vim"

- name: "vundle > install"
  with_items:
    - "{{ primary_user }}"
  win_command: "git clone https://github.com/VundleVim/Vundle.vim.git {{ item.home }}/.vim/bundle/vundle"
  args:
    creates: "{{ item.home }}/.vim/bundle/vundle"
  tags:
    - "vim"

##################################################################

