---

#################################################################

- name: "apt | install"
  apt:
    name    : "{{ item }}"
    state   : "latest"
  with_items: "{{ libraries_apt }}"
  tags:
    - developer

- name: "pip | install"
  pip:
    name    : "{{ item }}"
    state   : "latest"
  with_items: "{{ libraries_pip }}"
  tags:
    - developer

#################################################################

