---

#################################################################

- name: "pip | install packages"
  pip:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ libraries_pip }}"
  tags:
    - powerline-shell

#################################################################

- name: "copy | .powerline-shell.json"
  template:
    src: ".powerline-shell.json.j2"
    dest: "{{ item.home }}/.powerline-shell.json"
    owner: "{{ item.id }}"
    group: "{{ item.id }}"
    mode: 0644
  with_items: "{{ all_users }}"
  tags:
    - powerline-shell

#################################################################

- name: "copy | fonts"
  copy:
    src: "PowerlineSymbols.otf"
    dest: "/usr/local/share/fonts/"
    owner: root
    group: root
    mode: 0644
  when: gui
  tags:
    - powerline-shell

- name: "copy | font config"
  copy:
    src: "10-powerline-symbols.conf"
    dest: "{{ item.home }}/.config/fontconfig/fonts.conf/"
    owner: "{{ item.id }}"
    group: "{{ item.id }}"
    mode: 0644
  with_items: "{{ all_users }}"
  when: gui
  tags:
    - powerline-shell

#################################################################

