---

- hosts: retropi
  become: yes
  become_method: sudo
  connection: local
  gather_facts: yes

  vars:
  - gui: false

  pre_tasks:
  - debug:
      msg: "Any prereq tasks go here"

  roles:
  - { role: prereq }

