---

#################################################################

- hosts         : retropie
  become        : yes
  become_method : sudo
  gather_facts  : yes


  vars:
    - proxy     : False

      pi_user     : "{{ primary_user }}"
      all_users:
        - "{{ root_user     }}"
        - "{{ primary_user  }}"

#################################################################

  roles:
    - { role: checks                                                                                            }
    - { role: users                                                                                             }

    - { role: prereq                                                                                            }





    - { role: git                                                                                               }
    - { role: ssh                                                                                               }
    - { role: shell,                    bash_welcome        : "retropie"                                        }
    - { role: vim                                                                                               }
    - { role: powerline                                                                                         }
    - { role: general                                                                                           }

    - { role: dev/framework/ansible                                                                             }

    - { role: retropie                                                                                          }

#################################################################

