---

- hosts         : retropie
  become        : yes
  become_method : sudo
  gather_facts  : yes


  vars:
    - proxy     : False

      pi_user:   { id : 'pi',     home : '/home/pi', name : 'pi',    email : 'pi@pi.com'     }
      all_users:
        - "{{ root_user     }}"
        - "{{ primary_user  }}"
        - "{{ pi_user       }}"

  roles:
    - { role: checks                                                                                            }
    - { role: users                                                                                             }
    - { role: prereq                                                                                            }

    - { role: git                                                                                               }
    - { role: ssh                                                                                               }
    - { role: bash,                     bash_welcome        : "retropie"                                        }
    - { role: vim                                                                                               }
    - { role: powerline                                                                                         }
    - { role: general                                                                                           }

    - { role: retropie                                                                                          }

