---

- hosts         : retropie
  become        : yes
  become_method : sudo
  gather_facts  : yes

  vars:
    - gui       : False
      proxy     : False

      root_user:
        id      : 'root'
        home    : '/root'
        name    : 'root'
        email   : 'root@root.com'

      primary_user:
        id      : 'pi'
        home    : '/home/pi'
        name    : 'Steve Stevens'
        email   : 'steve.h.i.stevens@gmail.com'

      all_users:
        - '{{ root_user }}'
        - '{{ primary_user }}'

  pre_tasks:
    - debug:
        msg: "Distribution: {{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      tags : ["always"]
    - debug:
        msg: "VM Status   : {{ ansible_virtualization_role }} [{{ ansible_virtualization_type }}]"
      tags : ["always"]

  roles:
    - { role: prereq                          }
    - { role: git                             }
    - { role: ssh                             }
    - { role: bash                            ,
          bash_welcome        : "retropie"    }
    - { role: vim                             }
    - { role: powerline-shell                 }
    - { role: general                         }
    - { role: retropie                        }

