---

- hosts: localhost
  become: yes
  become_method: sudo
  connection: local
  gather_facts: yes

  vars:
    - gui: True
      root_user:
        name: 'root'
        home: '/root'
        description: 'root'
        email: 'root@root.com'
      primary_user:
        name: 'steve'
        home: '/home/steve'
        description: 'Steve Stevens'
        email: 'steve.h.i.stevens@gmail.com'
      all_users:
        - '{{ root_user }}'
        - '{{ primary_user }}'

  pre_tasks:
    - debug:
        msg: "Any prereq tasks go here"

  roles:
    - { role: prereq }
    - { role: git }
    - { role: vim }
    - { role: powerline-shell }
    - { role: java }
    - { role: general }
    - { role: wallpaper }
    - { role: system-monitor }

