---

#################################################################

- hosts         : localhost
  gather_facts  : yes
  connection    : local
  become        : yes
  become_method : sudo

  vars:
    - is_proxy     : False
    - all_users:
        - "{{ primary_user  }}"
        - "{{ root_user     }}"




#################################################################

  roles:
    - { role: checks                                                                                            }
    - { role: users                                                                                             }
    - { role: desktop                                                                                           }
    - { role: prereq                                                                                            }

    - { role: network                                                                                           }

    - { role: git                                                                                               }
    - { role: ssh                                                                                               }
    - { role: shell                                                                                             }
    - { role: vim                                                                                               }
    - { role: powerline                                                                                         }
    - { role: general                                                                                           }
    - { role: keychain                                                                                          }
    - { role: wallpaper                                                                                         }
    - { role: system-monitor                                                                                    }
    - { role: terminator                                                                                        }

    - { role: browser/chrome                                                                                    }

    - { role: dev/lang                                                                                          }
    - { role: dev/util                                                                                          }
    - { role: dev/framework                                                                                     }
    - { role: dev/ide                                                                                           }
    - { role: dev/data                                                                                          }

    - { role: media                                                                                             }

#################################################################

