---

- hosts: localhost
  become: yes
  become_method: sudo
  connection: local
  gather_facts: yes

  vars:
  - gui: true

  pre_tasks:
  - debug:
      msg: "Any prereq tasks go here"

  roles:
  - { role: prereq }
  - { role: general }
  - { role: vim }
  - { role: developer }

