---

- hosts         : localhost
  become        : yes
  become_method : sudo
  connection    : local
  gather_facts  : yes

  vars:
    - gui       : True
      proxy     : True

      root_user:
        id      : 'root'
        home    : '/root'
        name    : 'root'
        email   : 'root@root.com'

      primary_user:
        id      : 'engineer'
        home    : '/home/engineer'
        name    : 'Steve Stevens'
        email   : 'steven.stevens@travisperkins.co.uk'

      all_users:
        - '{{ root_user }}'
        - '{{ primary_user }}'

  pre_tasks:
    - debug:
        msg: "Distribution: {{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      tags: [ "always" ]
    - debug:
        msg: "VM Status   : {{ ansible_virtualization_role }} [{{ ansible_virtualization_type }}]"
      tags: [ "always" ]

  roles:
    - { role: prereq                          }
    - { role: git                             }
    - { role: bash                            }
    - { role: vim                             }
    - { role: powerline-shell                 }
    - { role: java                            }
    - { role: general                         }
    - { role: keychain                        }
    - { role: wallpaper                       }
    - { role: system-monitor                  }
    - { role: google-chrome                   }
    - { role: terminator                      }

    - { role: developer/general               }
    - { role: developer/tomcat                }
    - { role: developer/intellij              ,
          intellij_year       : "2017.3"      ,
          intellij_subversion : "2"           }
    - { role: developer/pycharm               ,
          pycharm_year        : "2018.1"      ,
          pycharm_subversion  : "2"           }
    - { role: developer/android               ,
          android_version     : "3.0.1.0"     ,
          android_build       : "171.4443003" }
    - { role: developer/gradle                ,
          gradle_version      : "4.1"         }
    - { role: developer/terraform             }
    - { role: developer/docker                }
    - { role: developer/awscli                }

    - { role: work/forticlient                }

  environment:
    http_proxy  : http://127.0.1.1:3128
    https_proxy : http://127.0.1.1:3128

