---

- hosts         : localhost
  become        : yes
  become_method : sudo
  gather_facts  : yes
  connection    : local

  vars:
    - gui       : True
      proxy     : False

      root_user: { id : 'root',   home : '/root',    name : 'root',  email : 'root@root.com' }

      all_users:
        - "{{ root_user     }}"
        - "{{ primary_user  }}"


  roles:
    - { role: checks                                                                                            }
    - { role: users                                                                                             }
    - { role: prereq                                                                                            }


    - { role: work/forticlient                                                                                  }

    - { role: git                                                                                               }
    - { role: ssh                                                                                               }
    - { role: bash                                                                                              }
    - { role: vim                                                                                               }
    - { role: powerline-shell                                                                                   }
    - { role: general                                                                                           }
    - { role: java                                                                                              }
    - { role: keychain                                                                                          }
    - { role: wallpaper                                                                                         }
    - { role: system-monitor                                                                                    }
    - { role: browsers/chrome                                                                                   }
    - { role: terminator                                                                                        }


    - { role: developer/general                                                                                 }
    - { role: developer/gradle                                                                                  }
    - { role: developer/maven                                                                                   }

    - { role: developer/terraform,      terraform_version   : "0.11.7"                                          }
    - { role: developer/docker                                                                                  }
    - { role: developer/awscli                                                                                  }

    - { role: developer/ide/intellij                                                                            }
    - { role: developer/ide/pycharm                                                                             }
    - { role: developer/ide/android                                                                             }

    - { role: media/steam                                                                                       }

