---

- hosts: localhost
  become: yes
  become_method: sudo
  connection: local
  gather_facts: yes

  vars:
    - gui: True
      root_user:
        - name: 'root'
          home: '/root'
      primary_user:
        - name: 'steve'
          home: '/home/steve'
      all_users:
        - '{{ root_user }}'
        - '{{ primary_user }}'

  pre_tasks:
    - debug:
        msg: "Any prereq tasks go here"

  roles:
    - { role: prereq }
    - { role: vim }
    - { role: powerline-shell }
    - { role: general }
    - { role: wallpaper }

