---

#################################################################

- hosts         : windows
  gather_facts  : yes
  connection    : local



  vars:
    - proxy     : False
    - all_users:
        - "{{ primary_user  }}"

    - ansible_connection                    : "winrm"
    - ansible_winrm_transport               : "ntlm"
    - ansible_winrm_server_cert_validation  : "ignore"

#################################################################

  roles:
    - { role: checks                                                                                            }
    - { role: users                                                                                             }
    - { role: desktop                                                                                           }
    - { role: prereq                                                                                            }


    - { role: network/dns                                                                                       }
    - { role: network/forticlient                                                                               }

    - { role: git                                                                                               }
    - { role: ssh                                                                                               }
    - { role: shell                                                                                             }
    - { role: vim                                                                                               }
    - { role: powerline                                                                                         }
    - { role: general                                                                                           }
    - { role: keychain                                                                                          }
    - { role: wallpaper                                                                                         }
    - { role: system-monitor                                                                                    }
    - { role: browser/chrome                                                                                    }
    - { role: browser/firefox                                                                                   }
    - { role: terminator                                                                                        }

    - { role: dev/lang/java                                                                                     }
    - { role: dev/lang/ruby                                                                                     }

    - { role: dev/postman                                                                                       }

    - { role: dev/docker                                                                                        }
    - { role: dev/framework/ansible                                                                             }
    - { role: dev/framework/awscli                                                                              }
    - { role: dev/framework/gradle                                                                              }
    - { role: dev/framework/maven                                                                               }
    - { role: dev/framework/terraform                                                                           }




    - { role: dev/ide/intellij                                                                                  }
    - { role: dev/ide/pycharm                                                                                   }
    - { role: dev/ide/android                                                                                   }
    - { role: dev/ide/mongorobot3                                                                               }

    - { role: media/steam                                                                                       }
    - { role: media/plex                                                                                        }

#################################################################

