---
# ################################################################

- name: "Mkdirs"
  with_items:
    - "{{ pycharm.home }}/{{ pycharm_version }}"
  ansible.builtin.file:
    name: "{{ item }}"
    state: "directory"
    recurse: "yes"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    mode: "0755"
  tags:
    - "{{ pycharm.tags }}"

#################################################################

- name: "Apt > install"
  ansible.builtin.apt:
    name: "{{ pycharm.libraries.apt }}"
    state: "latest"
  tags:
    - "{{ pycharm.tags }}"

#################################################################

- name: "Unpack > application"
  become: true
  become_user: "{{ primary_user.id }}"
  ansible.builtin.unarchive:
    src: "{{ pycharm.url }}{{ pycharm.zip }}"
    dest: "{{ pycharm.home }}/{{ pycharm_version }}"
    remote_src: "yes"
    extra_opts: [--strip-components=1]
    creates: "{{ pycharm.home }}/{{ pycharm_version }}/bin/"
  tags:
    - "{{ pycharm.tags }}"

#################################################################

- name: "Launcher > desktop icon"
  ansible.builtin.template:
    src: "{{ desktop }}.desktop.j2"
    dest: "/usr/share/applications/{{ desktop }}.desktop"
    owner: "{{ primary_user.id }}"
    group: "{{ primary_user.id }}"
    mode: "0644"
  tags:
    - "{{ pycharm.tags }}"
    - "launcher"

- name: "Launcher > add"
  become: true
  become_user: "{{ primary_user.id }}"
  ansible.builtin.script: "../../../scripts/add_{{ desktop_environment }}_launcher.sh {{ desktop }}"
  changed_when: false
  tags:
    - "{{ pycharm.tags }}"
    - "launcher"

#################################################################
