---

#################################################################

- name: "mkdirs"
  with_items:
    - "{{ pycharm.home }}/{{ pycharm_version }}"
  file:
    name    : "{{ item }}"
    state   : "directory"
    recurse : "yes"
    owner   : "{{ primary_user.id }}"
    group   : "{{ primary_user.id }}"
    mode    : "0755"
  tags:
    - "{{ pycharm.tags }}"

#################################################################

- name: "apt > install"
  apt:
    name    : "{{ pycharm.libraries.apt }}"
    state   : "latest"
  tags:
    - "{{ pycharm.tags }}"

#################################################################

- name: "unpack > application"
  become : yes
  become_user : "{{ primary_user.id }}"
  unarchive:
    src         : "{{ pycharm.url }}{{ pycharm.zip }}"
    dest        : "{{ pycharm.home }}/{{ pycharm_version }}"
    remote_src  : "yes"
    extra_opts  : [--strip-components=1]
    creates     : "{{ pycharm.home }}/{{ pycharm_version }}/bin/"
  tags:
    - "{{ pycharm.tags }}"

#################################################################

- name: "launcher > desktop icon"
  template:
    src   : "{{ desktop }}.desktop.j2"
    dest  : "/usr/share/applications/{{ desktop }}.desktop"
    owner : "{{ primary_user.id }}"
    group : "{{ primary_user.id }}"
    mode  : "0644"
  tags:
    - "{{ pycharm.tags }}"
    - "launcher"

- name    : "launcher > add"
  become : yes
  become_user : "{{ primary_user.id }}"
  script  : "../../../scripts/add_{{ desktop_environment }}_launcher.sh {{ desktop }}"
  changed_when: False
  tags:
    - "{{ pycharm.tags }}"
    - "launcher"

#################################################################

